### ISSUE TITLE
breakTheGlass feature fails to work properly

### ISSUE THREAD

**Issue by madAndroid** [weaveworks/tf-controller#1008]
I'm having problems when attempting to use the breakTheGlass functionality, this is the output I get:

```shell
tfctl break-glass vpc
 Break the glass requested for flux-system/vpc
Waiting:  Initializing
Waiting:  Initializing
Waiting:  Initializing
Waiting:  Initializing
Waiting:  Initializing
Waiting:  Initializing
Waiting:  Initializing
Waiting:  Initializing
Waiting:  Initializing
Waiting:  Initializing
Waiting:  Initializing
Waiting:  Initializing
Waiting:  Initializing
Waiting:  Initializing
Waiting:  Initializing
Waiting:  Initializing
Waiting:  Breaking the glass is not allowed
Error: breaking the glass is not allowed
```

Here is my `Terraform` definition:

```yaml
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: vpc
  namespace: flux-system
spec:
  alwaysCleanupRunnerPod: true
  approvePlan: auto
  breakTheGlass: true
  destroy: false
  destroyResourcesOnDeletion: true
  disableDriftDetection: false
  enableInventory: true
  force: false
  interval: 1h
  parallelism: 0
  path: ./distributed-databases/cloudnative-postgres
  refreshBeforeApply: false
  runnerPodTemplate:
    metadata: {}
    spec:
      env:
      - name: AWS_DEFAULT_REGION
        value: us-west-1
      - name: AWS_REGION
        value: us-west-1
  runnerTerminationGracePeriodSeconds: 30
  serviceAccountName: tf-runner
  sourceRef:
    kind: GitRepository
    name: data-on-eks
    namespace: flux-system
  storeReadablePlan: human
  targets:
  - module.vpc
  vars:
  - name: name
    value: data-on-eks-cn-postgres
  - name: region
    value: us-west-1
  - name: eks_cluster_version
    value: "1.25"
  - name: vpc_cidr
    value: 10.1.0.0/16
  workspace: default
```

I have the `.spec.breakTheGlass` set to `true`, and I have made sure the latest HelmRelease is installed, and the `apiVersion` is `v1alpha2`

Versions:
```
helm ls -A --all | grep tf-controller
tf-controller           flux-system             5               2023-09-20 07:23:06.049394615 +0000 UTC deployed        tf-controller-0.16.0-rc.3       v0.16.0-rc.3

kc get deployments.apps -n flux-system tf-controller -o jsonpath='{.spec.template.spec.containers[*]}' | jq '.image'
"ghcr.io/weaveworks/tf-controller:v0.16.0-rc.3"
```
