### ISSUE TITLE
[Investigate] No terraform is created when using Branch Planner 

### ISSUE THREAD

**Issue by zerunhu** [weaveworks/tf-controller#1065]
I encountered some issues while using Branch Planner. https://weaveworks.github.io/tf-controller/branch_planner/getting-started/

My steps:

1. Installed Branch Planner using kubectl apply -f https://raw.githubusercontent.com/weaveworks/tf-controller/fa4b3b85d316340d897fda4fed757265ba2cd30e/docs/branch_planner/release.yaml
2. Created the relevant resources. 
`kubectl create secret generic branch-planner-token     --namespace=flux-system     --from-literal="token=${mytoken}"`
```
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: atlantis
  namespace: flux-system
spec:
  interval: 30s
  url: https://github.com/zerunhu/atlantis.git
  ref:
    branch: main

---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: demo
  namespace: flux-system
spec:
  interval: 1m
  approvePlan: auto
  path: ./
  sourceRef:
    kind: GitRepository
    name: atlantis
    namespace: flux-system
  writeOutputsToSecret:
    name: at-output
  varsFrom:
  - kind: Secret
    name: tf-secret-test
```
3. Submitted a Pull requests.  https://github.com/zerunhu/atlantis/pull/6

However, the Terraform resources(demo) only keep retrying erroneously on my main branch because the resource names in my main branch are defined repeatedly. It did not detect the creation of any new Terraform resources.

Additionally, regarding the How does it work? section in the document https://weaveworks.github.io/tf-controller/branch_planner, does Branch Planner only output the results of the Terraform plan in the comment, does it perform other operations? If I approve this pull request, what to do next in the process. will it continue with the normal Terraform operations? In this case, will it pass the tfplan file to ensure that the Terraform apply on my main branch is consistent with the plan output when I made the pull request?
