### ISSUE TITLE
Branch planner PR's assume empty state

### ISSUE THREAD

**Issue by YentlFrickx** [weaveworks/tf-controller#1163]
I set up the tf-controller in my cluster and it works without issue for applying changes in the 'main' branch. But using the branch planner functionality I noticed that on every PR I create, it starts from an empty state instead of from the state from the main branch. This results in all resources seemingly being created for the first time, not changed or added.

**Comment by jsimpso** [comment]
I just ran into this too, it looks like it's due to how `secretSuffix` is being dynamically assigned in the backend config when not specified in the spec.

For a Terraform object named `testing`, the default `secretSuffix` is `testing`. However, for a branch-planner PR object, the default `secretSuffix` ends up being `testing-pr-{pr_id}`.

This can be worked around with the default backend by manually specifying `secretSuffix` in your [backendConfig](https://weaveworks.github.io/tf-controller/References/terraform/#infra.contrib.fluxcd.io/v1alpha2.BackendConfigSpec) , e.g.

```yaml
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: helloworld
  namespace: flux-system
spec:
  interval: 1m
  approvePlan: auto
  path: ./
  backendConfig:
    secretSuffix: helloworld
  sourceRef:
    kind: GitRepository
    name: helloworld
    namespace: flux-system
```
