### ISSUE TITLE
Use object in VarsFrom

### ISSUE THREAD

**Issue by abhishekPa1** [weaveworks/tf-controller#1174]
I am trying to pass output from one TF module to another.

I have below vars and varsFrom sections for a `resource2` which is dependent on a `resource1`

> **resource2**

```
vars:
  - name: length
    value:
      val: 20

varsFrom:
  - kind: Secret
    name: secretResource1
```
I want the `val:20` to be substituted by a value in secret `secretResource1`

secret `secretResource1` is created by writing the outputs from resource1 using `writeOutputsToSecret`.

I tried doing the below in `resource1` but it does not work

```
writeOutputsToSecret:
    name: secretResource1
    outputs:
    - resultofinteger:length.val
```
If the length variable was flat like below

```
vars:
  - name: length
    value: 20
```

Something like below works fine

```
writeOutputsToSecret:
    name: secretResource1
    outputs:
    - resultofinteger:length
```

So how can I substitute the object value here. I know another option is to use `values` like [here](https://docs.gitops.weave.works/docs/terraform/Using%20Terraform%20CRD/depends-on/) . But that would need us to redesign our TF module which we want to avoid.
