### ISSUE TITLE
Making the default runner pod role least privileged

### ISSUE THREAD

**Issue by chanwit** [weaveworks/tf-controller#127]
Currently, we have the default TF-runner role as the following:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    infra.contrib.fluxcd.io/tenant: dev-team
  name: dev-team-tf-runner
  namespace: app-01
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - "coordination.k8s.io"
  resources:
  - leases
  verbs:
  - "*"
```
because the runner pod needs to access ConfigMaps, Secrets and the Terraform binary needs to acquire Lease to lock its TF-state.

It is a must to review to see if we could remove some verbs like "watch" or "patch" if they're not required.

Also another non-K8s backend, like S3 when we support it, should not require an access to Lease.
