### ISSUE TITLE
Add a test case for writing output with dots in its name to a secret

### ISSUE THREAD

**Issue by chanwit** [weaveworks/tf-controller#128]
Need a test case to make sure that outputs containing dots, like the following, in their names are allowed:

```yaml
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: master-key-tf
  namespace: app-01
spec:
  interval: 1h
  path: ./_artifacts/10-zz-terraform
  writeOutputsToSecret:
    name: age
    outputs:
    - age.agekey
```

**Comment by chanwit** [comment]
Confirmed that Terraform does not support "." in the output.

We need a mapping like this:
```
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: master-key-tf
  namespace: app-01
spec:
  interval: 1h
  path: ./_artifacts/10-zz-terraform
  writeOutputsToSecret:
    name: age
    outputs:
    - age_agekey:age.agekey
```
