### ISSUE TITLE
Improve API of the write outputs spec

### ISSUE THREAD

**Issue by chanwit** [weaveworks/tf-controller#131]
Per @phoban01 suggestion,

```yaml
writeOutputs:
   - kind: Secret
     name: helloworld-output
     outputs:
     - key: age_key
       targetPath: age.agekey
```

This should be re-implemented as part of the `v1alpha2 spec.
