### ISSUE TITLE
Add example docs on how to use  `varsFrom` with a secret

### ISSUE THREAD

**Issue by aclevername** [weaveworks/tf-controller#152]
Hello :wave: awesome project! I was playing around with trying to use `varsFrom` to create a AWS resource using some access/secret keys in a secret, and was unable to get it working. It would be great to see an example in the docs :smile: . To workaround the problem I in-lined the secrets into the terraform CRD. 

I attempted this (creds redacted)
```
kubectl create secret -n wego-system generic aws-creds --from-literal=access=bar --from-literal=secret=foo

k -n wego-system get secret aws-creds -o yaml
apiVersion: v1
data:
  access: YmFy
  secret: Zm9v
kind: Secret
```

```
---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: auto-apply-terraform
  namespace: wego-system
spec:
  interval: 1m
  approvePlan: "auto"
  path: ./
  sourceRef:
    kind: GitRepository
    name: wego-auto-github-gitops
    namespace: wego-system
  varsFrom:
  - kind: Secret
    name: aws-creds
    namespace: wego-system
    varsKeys:
    - access
    - secret
```

With template file:
```
variable "access" {
  type = string
}

variable "secret" {
  type = string
}

provider "aws" {
  region     = "us-west-2"
  access_key = var.access
  secret_key = var.secret
}

...
```

Am I missing something? This is with `0.7.0`

thanks!
