### ISSUE TITLE
Failing to verify artefact with env proxy

### ISSUE THREAD

**Issue by oliverbaehler** [weaveworks/tf-controller#167]
I am not really sure if i am just to stupid, but i keep getting the following message:

```
{"level":"error","ts":"2022-03-15T21:26:01.284Z","logger":"controller.terraform","msg":"Reconciliation failed after 3.886180395s, next try in 1m0s","reconciler group":"infra.contrib.fluxcd.io","reconciler kind":"Terraform","name":"helloworld-3","namespace":"flux-system","revision":"main/ece7cf37ed2bde070e2e3117bb25dcf04ae82fa4","error":"failed to verify artifact: computed checksum 'a178d6af210cb22825e40a879dc892bf7099091e2bd2ee5ad9697a7b12409aa2' doesn't match advertised 'd2c7fe7ea7e54c2f695c191ff4c3131567389f3c7a6e18a9d422ccc80ba6ed18'"}
```

The Terraform looks like this:

```
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: helloworld-3
  namespace: flux-system
spec:
  approvePlan: "auto"
  path: ./services/harbor/tenant/
  interval: "1m"
  sourceRef:
    kind: GitRepository
    name: tf-catalog
    namespace: flux-system
  vars:
  - name: password
    value: "none"
  - name: project
    value: "example"
```

The gitRepository status seems to be fine as well:

```
status:
  artifact:
    checksum: d2c7fe7ea7e54c2f695c191ff4c3131567389f3c7a6e18a9d422ccc80ba6ed18
    lastUpdateTime: "2022-03-15T21:09:38Z"
    path: gitrepository/flux-system/tf-catalog/ece7cf37ed2bde070e2e3117bb25dcf04ae82fa4.tar.gz
    revision: main/ece7cf37ed2bde070e2e3117bb25dcf04ae82fa4
    url: http://source-controller.flux-system.svc.cluster.local./gitrepository/flux-system/tf-catalog/ece7cf37ed2bde070e2e3117bb25dcf04ae82fa4.tar.gz
  conditions:
  - lastTransitionTime: "2022-03-15T21:09:38Z"
    message: 'Fetched revision: main/ece7cf37ed2bde070e2e3117bb25dcf04ae82fa4'
    reason: GitOperationSucceed
    status: "True"
    type: Ready
  observedGeneration: 1
  url: http://source-controller.flux-system.svc.cluster.local./gitrepository/flux-system/tf-catalog/latest.tar.gz
```
I downloaded the `ece7cf37ed2bde070e2e3117bb25dcf04ae82fa4.tar.gz` and got the same checksum trough `sha256sum`:

```
$ sha256sum ece7cf37ed2bde070e2e3117bb25dcf04ae82fa4.tar.gz

d2c7fe7ea7e54c2f695c191ff4c3131567389f3c7a6e18a9d422ccc80ba6ed18  ece7cf37ed2bde070e2e3117bb25dcf04ae82fa4.tar.gz
```

I believe this happens because I have to set a proxy (bcs of company stuff). So then I add the following environment variables:

```
 env:
        - name: HTTP_PROXY
          value: http://company.proxy
        - name: HTTPS_PROXY
          value: http://company.proxy
        - name: NO_PROXY
          value: localhost,127.0.0.1,.cluster.local,10.0.0.0/8
``` 

That's the only thing that differs from the default installation. But if i remove those, I get the following:

```
{"level":"info","ts":"2022-03-15T21:35:09.000Z","logger":"controller.terraform","msg":"new terraform","reconciler group":"infra.contrib.fluxcd.io","reconciler kind":"Terraform","name":"helloworld-3","namespace":"flux-system","workingDir":"/tmp/flux-system-helloworld-3-227125539/services/harbor/tenant"}
{"level":"info","ts":"2022-03-15T21:35:09.216Z","logger":"controller.terraform","msg":"clean up dir: ok","reconciler group":"infra.contrib.fluxcd.io","reconciler kind":"Terraform","name":"helloworld-3","namespace":"flux-system"}
{"level":"error","ts":"2022-03-15T21:35:09.228Z","logger":"controller.terraform","msg":"Reconciliation failed after 14.522177049s, next try in 1m0s","reconciler group":"infra.contrib.fluxcd.io","reconciler kind":"Terraform","name":"helloworld-3","namespace":"flux-system","revision":"main/ece7cf37ed2bde070e2e3117bb25dcf04ae82fa4","error":"error running Init: rpc error: code = Unknown desc = exit status 1\n\nError: Failed to query available provider packages\n\nCould not retrieve the list of available versions for provider\nbestseller/harbor: could not connect to registry.terraform.io: Failed to\nrequest discovery document: Get\n\"https://registry.terraform.io/.well-known/terraform.json\": dial tcp\n-:443: connect: connection refused\n\n"}
```

That looks already better to me, meaning it doesn't fail at validating the artefact. Obviously I can't connect to the outside world. Has anyone an idea why the set proxy would change the checksum?
