### ISSUE TITLE
How does the runner image import the provider package as a local tf repository

### ISSUE THREAD

**Issue by huzerun0306** [weaveworks/tf-controller#191]
After the terraform init command is executed, the provider package will be downloaded, which will be downloaded from the local repository or the remote repository. I want to use a local repository for two reasons:
https://www.terraform.io/cli/config/config-file#explicit-installation-method-configuration
1. For network reasons, the local warehouse is faster
2. My custom provider does not want to be provided to the official repository, but only for internal use, so I want to directly put my provider package into the runner image to build a local repository
When using the local repository, you need to put it in a specific directory:
~/.terraform.d/plugins/${host_name}/${namespace}/${type}/${version}/${target}

I created a folder in the dockerfile and put the provider package in it, but the runner still downloads the provider package from the Internet
`RUN mkdir -p /home/controller/.terraform.d/plugins/tencent.com/ieg/kubegame/1.0.0/linux_amd64/  && mkdir -p /home/controller/.terraform.d/plugins/registry.terraform.io/hashicorp/tencentcloud/1.60.5/linux_amd64`

I enter the runner's pod to see if provdier exists
![image](https://user-images.githubusercontent.com/44351924/160624365-7736a6e1-9466-4f9f-8526-14c3c5395839.png)
I checked the log of the pod of tf-controller and found that the provider was downloaded from the Internet
![image](https://user-images.githubusercontent.com/44351924/160625270-70e09265-4d5b-4aee-a1c8-7b2d337dbe18.png)

I checked the Dockerfile of the runner, whether there is a unified private provider management in the project

**Comment by chanwit** [comment]
You shouldn't add anything to the controller image. 

Best bet would be putting your provider binaries to your Runner image.
Using the same `RUN ADD`, I think you would do the followings:

1. Prepare your custom runner, say `customRunner.Dockerfile`:
```
FROM ghcr.io/weaveworks/tf-runner:v0.9.3

RUN mkdir -p /home/controller/.terraform.d/plugins/tencent.com/ieg/kubegame/1.0.0/linux_amd64/ \
        && mkdir -p /home/controller/.terraform.d/plugins/registry.terraform.io/hashicorp/tencentcloud/1.60.5/linux_amd64

```
2. `docker build -t tf-runner:custom -f customRunner.Dockerfile .`
3. In TF-controller's Deployment, you would change the line:
```yaml
spec:
  containers:
  - args:
    - --watch-all-namespaces
    - --log-level=info
    - --log-encoding=json
    - --enable-leader-election
    - --concurrent=1
    command:
    - /sbin/tini
    - --
    - tf-controller
    env:
    - name: RUNTIME_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: RUNNER_POD_IMAGE
      value: tf-runner:custom # Put your image here
```

If you're deploying TF-controller via its HelmChart, here's how to configure the Runner Pod Image:
https://github.com/weaveworks/tf-controller/blob/main/charts/tf-controller/values.yaml#L24
