### ISSUE TITLE
Add Support for HCL in `varsFrom`

### ISSUE THREAD

**Issue by Nalum** [weaveworks/tf-controller#196]
Outlining this here before I start on an implementation.

`ConfigMap`/`Secret` do not support types other than strings, the `varsFrom[].varsKeys` allows selecting which keys in the `ConfigMap`/`Secret` are used. Proposal to update this to also allow specifying a type e.g. `hcl` thereby allowing more complex data in the `ConfigMap`/`Secret`.

Example:
`ConfigMap`:
```yaml
data:
  arrayOfIPs: -|
    ["127.0.0.1", "127.0.0.2", "127.0.0.3"]
```

`Terraform`:
```yaml
varsFrom:
- kind: ConfigMap
  varsKeys:
  - name: arrayOfIPs
    type: hcl
```

Some questions:
- Should `type` be optional?
- Should there be another parameter to say import all keys from the `ConfigMap`/`Secret` but those in `varsKeys` need attention?
  e.g. 
  ```yaml
  varsFrom:
  - kind: ConfigMap
    allKeys: true
    varsKeys:
    - name: arrayOfIPs
      type: hcl
  ```

**Comment by akselleirv** [comment]
Would also be great if it was possible to have a JSON value of complex type. For example:
```
apiVersion: v1
kind: ConfigMap
data:
  identities: '[{"service_account":{"name":"test-sa","namespace":"flux-system"},"cluster":{"name":"kind-cluster","resource_group_name":"kind-local"}}]'
  name: workload-identity-sample
  namespace: flux-system
```

A workaround I have for the moment is to accept a string in my Terraform module and use the `jsondecode` function to unmarshal it.
