### ISSUE TITLE
Optionally specify sub directory on SourceRef

### ISSUE THREAD

**Issue by steveww** [weaveworks/tf-controller#217]
Git repos often have docs, notes, test scripts, etc. included in them. At the moment updating the docs inside a repo causes the tf-controller to perform a plan. If it were possible to specify a sub directory to monitor inside the `sourceRef`, similar to [Flux Kustomize](https://fluxcd.io/docs/components/kustomize/kustomization/), then the plan would only be performed when required.

```yaml
sourceRef:
  kind: GitRepository
  name: foo
  namespace: bar
  path: foo/bar
```
