### ISSUE TITLE
[Proposal] Showing plan details 

### ISSUE THREAD

**Issue by chanwit** [weaveworks/tf-controller#22]
Seeing plan details is an very important feature for the plan step.
We need to have a mechanism to show plan details somewhere (via a notification? via a PR?)

**Comment by phoban01** [comment]
To me showing the plan in PR comment makes sense. I think this should work nicely with the manual approval feature already in place.

I like the approach of Atlantis: https://www.runatlantis.io/

**Comment by chanwit** [comment]
To implement an Atlantis-like workflow, we need to write back to a different branch,
and one of the possible ways is to include the whole readable plan as an extended message of the Git commit.

GitHub for example, will extract the extended message as the body of the PR, when we create it.
So the plan will be display nicely in the PR. That's a good thing.

Technically, an extended message of Git already allows a very large string to be there. But I'm not sure if it's a way to implement this feature, because the extended message will be inside the Git forever.  (Good for the audit process, maybe?)

**Comment by phoban01** [comment]
Interesting idea to use the commit message body; my sense is that this could quickly lead to bloated repositories / slow pulls, particularly with complex plans?  Perhaps https://github.com/fluxcd/go-git-providers plus the ability to add the plan in a PR comment  would cover our requirements here?

**Comment by chanwit** [comment]
Yeah `go-git-provider` solved the problem for us for the commit and push part. 

The more difficult problem is an ability to show plan details in a PR, for GitHub, GitLab, etc. I agree that this is the best approach we would take. But I haven't seen a good solution yet. Maybe we could check what Atlantis does.

**Comment by phoban01** [comment]
Something like this in the comment?
<details>
  <summary>View plan</summary>

 ```terraform

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_s3_bucket.test will be created
  + resource "aws_s3_bucket" "test" {
      + acceleration_status         = (known after apply)
      + acl                         = "private"
      + arn                         = (known after apply)
      + bucket                      = "test-bucket"
      + bucket_domain_name          = (known after apply)
      + bucket_regional_domain_name = (known after apply)
      + force_destroy               = false
      + hosted_zone_id              = (known after apply)
      + id                          = (known after apply)
      + region                      = (known after apply)
      + request_payer               = (known after apply)
      + tags                        = {
          + "Application" = "test"
          + "Environment" = "dev"
          + "Owner"       = "flux"
        }
      + tags_all                    = {
          + "Application" = "test"
          + "Environment" = "dev"
          + "Owner"       = "flux"
        }
      + website_domain              = (known after apply)
      + website_endpoint            = (known after apply)

      + versioning {
          + enabled    = (known after apply)
          + mfa_delete = (known after apply)
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + bucket     = (known after apply)
  + bucket_arn = (known after apply)

─────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't
guarantee to take exactly these actions if you run "terraform apply" now.

```
</details>

**Comment by chanwit** [comment]
Yes, agree.

**Comment by phoban01** [comment]
I think an API something like the below would be required to implement this feature. 

A couple of things to note:
- separate credentials would be required to access the git provider API
- if the PR branch exists should push the changes, otherwise creates the branch
- there's potentially enough logic here to warrant a dedicated controller and CR

```yaml
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: helloworld
  namespace: flux-system
spec:
  approvePlan: "auto"
  path: ./
  sourceRef:
    kind: GitRepository
    name: helloworld
    namespace: flux-system
  pullRequestAutomation:
    provider: github
    credentials:
        type: oauth | token
        secretRef:  # note: this must be an oauth credential not a deploy/ssh key
            name: provider-credential
    git: # similar to flux image update automation
        commit:
            author:
                name: flux-tf-controller
                email: fluxbot@example.com
            messageTemplate: |
                An automated update from FluxBot
                [ci skip]
            signingKey:
                secretRef:
                    name: git-pgp
        pullRequest:
            baseRef: main # branch to open pull request against
            push:
                prefix: tf-auto # prefix for PR branch name
                deleteOnMerge: true
            includePlanOutput: true # includes the terraform plan output in markdown
            messageTemplate: message body string
```
