### ISSUE TITLE
Recursive Path Selection

### ISSUE THREAD

**Issue by dfreilich** [weaveworks/tf-controller#269]
Hi! 

Is there any option to watch all files in a directory, recursively including subdirectories? 

I had tried setting up a `tf` object to deploy `redis`, and when I had the files as top-level files in my source directory, it successfully deployed. When I moved them into a `redis/` subdirectory, it no longer worked, which was not the expected behavior. 

My controller `spec` is as follows (with TF controller version [v0.10.0-rc.6](https://github.com/weaveworks/tf-controller/releases/tag/v0.10.0-rc.6)):
```
---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: staging
  namespace: flux-system
spec:
  approvePlan: "auto"
  destroyResourcesOnDeletion: true
  serviceAccountName: tf-controller
  refreshBeforeApply: true
  interval: 30s
  path: ./
  sourceRef:
    kind: GitRepository
    name: staging
    namespace: flux-system

```
