### ISSUE TITLE
Support OCI Repository

### ISSUE THREAD

**Issue by chanwit** [weaveworks/tf-controller#283]
Flux's Source controller v0.26.0+ introduces a new kind of source, called OCIRepository.
It would be great for us to support this source.

```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: helloworld-oci
spec:
  interval: 1m
  url: oci://ghcr.io/tf-controller/helloworld
  ref:
    tag: main
---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: helloworld-oci-auto-approve
spec:
  interval: 10s
  approvePlan: "auto"
  path: ./
  sourceRef:
    kind: OCIRepository
    name: helloworld-oci
```
