### ISSUE TITLE
Feature request: Support multiple authentication strategies and endpoints

### ISSUE THREAD

**Issue by artem-nefedov** [weaveworks/tf-controller#294]
It would be very useful if it was possible to tell tf-controller how to perform authentication and which endpoint to use explicitly (e.g. separate CRD?), and have multiple strategies active at the same time, similar to how Crossplane does it with ProviderConfig resource.

Example use case (this is possible to do with Crossplane):
I want to use the controller to create resources in both AWS and AWS China (which is a separate partition) from the same cluster. For AWS, I want to use IRSA, while for AWS China I want to use static user credentials stored in a Secret. Furthermore, in both cases I want controller to assume another role, and use that role to actually work with resources (because we have roles in different accounts, and original role/user from cluster owner's account is supposed to assume them).

**Comment by chanwit** [comment]
Thank you @artem-nefedov !!
This is for sure a practical feature request.

I reviewed the concept of Crossplane's providerConfig and found that we already support a similar mechanism with variables and service accounts. 

Please note that it's not the controller that assumes roles before provisioning; it's the runner on **separate pods**, with **different service account**, and you can optionally provide credentials via variables. You can even use the same cluster to provision resources for multi-clouds, for example.

Maybe we would discuss the use of existing mechanisms. If they're not covering your use cases, we can consider adding a concept similar to providerConfig to the controller.

**Comment by artem-nefedov** [comment]
Thanks for reaching out @chanwit .

Based on your explanation, I assume you mean [Customize runner pod](https://weaveworks.github.io/tf-controller/use_cases/#customize-runner-pod) section of the docs. It looks like it is possible to template runner pod. Going back to my usecase, does it mean that to use static IAM user for AWS China I would have to write Pod template all the way down to containers, and pass the values from Secret as env.variables, or is there a more convenient way to do it?

Furthermore, right now I don't see a way to make runner assume another role (e.g. in another account) after obtaining initial IAM identity. In Crossplane, I would do this by specifying `assumeRole.roleARN` in ProviderConfig.

For more clarify, here's actual Crossplane manifests our setup is based on.

AWS global ProviderConfigs (there are multiple of those, each one have different role):

```yaml
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: global
spec:
  assumeRole:
    roleARN: arn:aws:iam::00000000000:role/crossplane-admin
    externalID: some-external-id-string
  credentials:
    source: InjectedIdentity # pod gets IRSA role first, then assumes role specified above
```

AWS China (also has different roles, only only one static user):

```yaml
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: cn
spec:
  assumeRole:
    roleARN: arn:aws-cn:iam::00000000000:role/crossplane-admin
    externalID: some-external-id-string
  credentials:
    source: Secret # pod gets static IAM user first, then assumes role specified above
    secretRef:
      namespace: crossplane-system
      name: aws-cn-creds
      key: credentials
  endpoint: ... # this section contains info telling controller to use aws-cn api endpoints
```

Secret `aws-cn-creds`'s "credentials" field looks like this:

```
[default]
aws_access_key_id = <redacted>
aws_secret_access_key = <redacted>
```

**Comment by chanwit** [comment]
For static credentials, or in the case of assuming a role, you can use varsFromSecrets to solve both issues in Terraform ways.
You would prepare your TF files with the following blocks.

For AWS,
```hcl
variable "role_to_assume" { type = "string" } 
variable "external_id" { type = "string" } 
provider "aws" {
  assume_role {
    role_arn     = var.role_to_assume
    external_id  = var.external_id
  }
}
```

You can then supply values of those two variables.
```yaml
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: helloworld
  namespace: flux-system
spec:
  approvePlan: "auto"
  interval: 1m
  path: ./
  sourceRef:
    kind: GitRepository
    name: helloworld
    namespace: flux-system
  vars:
  - name: role_to_assume
    value: "arn:aws:iam::123456789012:role/ROLE_NAME"
  - name: external_id
    value: "EXTERNAL_ID"
```

For AWS China, use this config, and you supply your `aws-cn-creds`.
```hcl
variable "aws_access_key_id" { type = "string" } 
variable "aws_secret_access_key" { type = "string" } 
provider "aws" {
  access_key = var.aws_access_key_id
  secret_key = var.aws_secret_access_key
}
```
