### ISSUE TITLE
Helm chart: using runner ServiceAccount created by eksctl with imagePullSecrets

### ISSUE THREAD

**Issue by artem-nefedov** [weaveworks/tf-controller#296]
eksctl has built-in support for EKS IRSA, where it can create both IAM role and corresponding ServiceAccount in cluster based on defined manifest. With this approach, it makes sense to not create by helm ServiceAccount at all, so you would specify something like this in values:

```yaml
runner:
  serviceAccount:
    create: false
    name: tf-runner
```

The problem arises if you also need to use private image registry that requires authentication, so you also need `imagePullSecrets`. Currently, the chart adds `imagePullSecrets` to ServiceAccount instead of adding them to a Pod, which makes it hard to use this setup (eksctl doesn't support adding `imagePullSecrets` to ServiceAccount, so you'll have to perform extra step to patch SA it created).

For reference, every other chart that we use which also require IAM role to operate would always add `imagePullSecrets` to Pod.

I understand that this change is not as simple as just changing helm chart, because "tf-runner" doesn't exist there as a manifest, but instead generated by the controller at runtime, but I still hope you think about this, especially considering eksctl is also a Weave product.

**Comment by Nalum** [comment]
Another approach here could be to use annotations to associate the runner service account with your IRSA IAM Role:

```yaml
runner:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: [aws-arn-id]
```
