### ISSUE TITLE
Can't use different namespace

### ISSUE THREAD

**Issue by vbezhenar** [weaveworks/tf-controller#297]
I installed tf-controller using the following flux files:

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tf-controller
  namespace: tf-controller
spec:
  chart:
    spec:
      chart: tf-controller
      version: 0.4.3
      sourceRef:
        kind: HelmRepository
        name: tf-controller
  interval: 24h
```

I can see that it created service account `tf-runner` in namespace `tf-controller`:

```
kubectl get -A serviceaccounts |grep tf-runner
tf-controller            tf-runner                            1         12m
```

Now I'm trying to reconcile Terraform resource which is located in a different namespace.

```
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: users
  namespace: keycloak-system
spec:
  approvePlan: auto
  vars:
    - name: keycloak_administrator_password
      valueFrom:
        secretKeyRef:
          key: password
          name: keycloak-administrator
    - name: smtp_auth_password
      valueFrom:
        secretKeyRef:
          key: password
          name: smtp-auth
  interval: 24h
  sourceRef:
    kind: GitRepository
    name: cmctech-cluster-users
    namespace: flux-system
```

This does not work. I'm getting the following errors in controller:

```
{"level":"error","ts":"2022-08-16T12:19:57.013Z","logger":"controller.terraform","msg":"unable to lookup or create runner","reconciler group":"infra.contrib.fluxcd.io","reconciler kind":"Terraform","name":"users","namespace":"keycloak-system","error":"pods \"users-tf-runner\" is forbidden: error looking up service account keycloak-system/tf-runner: serviceaccount \"tf-runner\" not found"}
{"level":"error","ts":"2022-08-16T12:19:57.013Z","logger":"controller.terraform","msg":"Reconciler error","reconciler group":"infra.contrib.fluxcd.io","reconciler kind":"Terraform","name":"users","namespace":"keycloak-system","error":"pods \"users-tf-runner\" is forbidden: error looking up service account keycloak-system/tf-runner: serviceaccount \"tf-runner\" not found"}
```

I expect the controller to work across all namespaces in the cluster. Is it current limitation or did I miss some way to configure it? Should I install separate copy of tf-controller into every namespace with terraform resource?

**Comment by artem-nefedov** [comment]
I agree that this is a big deal. Originally, I assumed that tf-runner will always run in controller's namespace (flux-system), but apparently this isn't the case.

**Comment by chanwit** [comment]
It says the serviceaccount "tf-runner" is not found inside the "keycloak-system" namespace.

We use the Controller / Runner architecture.
You need to create the `tf-runner` serviceaccount in every namespace where you'd like to run Terraform.
For example, in this case your runner pods will be created inside "keycloak-system".

You might also be blocked by the " flux-system " network policy too if you run the controller outside the "flux-system" namespace as the controller requires downloading source BLOBs from Flux's Source controller.

**Comment by vbezhenar** [comment]
So if someone stumbles upon this, here's exact recipe that I used which seems to work for me.

1. Only use `flux-system` for helm install.
2. Create the following resources in the namespace where you want to put your `Terraform` resource:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tf-runner
  namespace: keycloak-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tf-runner-keycloak-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tf-runner-role
subjects:
  - kind: ServiceAccount
    name: tf-runner
    namespace: keycloak-system
```
