### ISSUE TITLE
Add Terraform's cluster role binding for notification controller 

### ISSUE THREAD

**Issue by chanwit** [weaveworks/tf-controller#315]

**Comment by k0da** [comment]
Any plans for this? I opened a PR against notification-controller to validate terraform Kind in Event source. But it being rejected. What would be the strategy. Would tf-controoller require kustomize controller in order to provider notification abilities?

https://github.com/fluxcd/notification-controller/pull/429

**Comment by chanwit** [comment]
No, please follow this guide:

[Enable notifications for third party controllers](https://fluxcd.io/flux/cheatsheets/bootstrap/#enable-notifications-for-third-party-controllers)

**Comment by chanwit** [comment]
May I know more about your scenario?
You're planning to run TF-controller only with Source controller + Notification controller?

Or you're bootstrapping Flux normally and add TF-controller layer?

**Comment by k0da** [comment]
we shit TF objects into tf-controller by fleet. We don't use flux cd. Just tf-controller + notification-controller + source-controller

**Comment by chanwit** [comment]
I see.
That would make a requirement for the new installation method.

Let's discuss.

**Comment by k0da** [comment]
```
defaultNamespace: tf-ctrl
helm:
  repo: https://fluxcd-community.github.io/helm-charts
  chart: flux2
  version: 1.6.1
  values:
    installCRDs: true
    helmcontroller:
      create: false
    imageautomationcontroller:
      create: false
    imagereflectorcontroller:
      create: false
    kustomizecontroller:
      create: false
    notificationcontroller:
      create: true
```
