### ISSUE TITLE
Implement webhook for the plan stage

### ISSUE THREAD

**Issue by chanwit** [weaveworks/tf-controller#325]
Adding a Webhook after the "plan" stage and before the "apply" stage would add many benefits to the workflow, including
- plan validation
- cost estimation

**Payload specification**
Content-type: `json`
Body:
```json
{
  "apiVersion": "infra.contrib.fluxcd.io/v1alpha1",
  "kind": "Terraform",
  "metadata": {
    "name": "helloworld",
    "namespace": "default"
  }
  "spec": {
    "path": "./tf"
  },
  "status": {
    "tfplan": {
    }
  }
}
```

pseudo status:
In the above payload, we'll have the **pseudo** status `status.tfplan` to contain a full Terraform plan in JSON format to the endpoint.

This process expects 200 to proceed to the next step.
And the apply process will not be processed if the webhook returns an error like 40x, or 50x.

**Security concerns**
- We have to whitelist these Webhook URLs at the controller-level before allowing them to be specified to the CRs.
- Webhook URLs must be "https" only by default.

**Actionable items**
  - [x] design webhooks in the API
  - [ ] implement POST requests for webhooks
  - [ ] add whitelist to the controller's arguments

Here's the proposed API:

```yaml
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: hello-world
  namespace: default
spec:
  webhooks:
  - stage: post-planning
    url: https://abc.xyz/
    enabled: true
    payloadType: "SpecAndPlan" # Possible values are: SpecAndPlan, SpecOnly, PlanOnly (default: SpecAndPlan)
    testExpression: "{{ .passed }}" # "true" or "false", "yes" or "no"
    errorMessageTemplate: "Message: {{ .message }}"
  - stage: post-planning
    url: https://def.xyz/
    enabled: true
```

**Comment by chanwit** [comment]
Here's the proposed API:

```yaml
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: hello-world
  namespace: default
spec:
  webhooks:
  - stage: post-planning
    url: https://abc.xyz/
    enabled: true
  - stage: post-planning
    url: https://def.xyz/
    enabled: true
```

**Comment by chanwit** [comment]
We would support only the `post-planning` stage for the current implementation.

**Comment by chanwit** [comment]
Webhooks would be processed one by one from top to bottom.
If a webhook returns 200, the process will continue to the next one.
If a webhook returns non-200, the process will stop, and the remaining webhooks will be skipped.

**Comment by chanwit** [comment]
We require a secretRef to refer to a TLS cert for each web hook too.

**Comment by chanwit** [comment]
Who's responsible for sending data to webhook and why?
  - Controller?
  - Runner?

**Comment by chanwit** [comment]
The controller should be responsible for posting data to webhooks so that the network policy can be centralized.

**Comment by bivas** [comment]
> In the above payload, we'll have the pseudo status status.tfplan to contain a full Terraform plan in JSON format to the endpoint.

This posses an issue with exiting services that knows how to process Terraform plans (JSON formatted). It will force the user to create a wrapper webhook (proxy) that will extract the `status.tfplan` content and forward it to the actual service.
If we were to keep this API, maybe add an ability to POST a raw Terraform plan content if requested. e.g.
```
spec:
  webhooks:
  - stage: post-planning
    url: https://abc.xyz/
    enabled: true
    rawPayload: true # will post the Terraform plan as raw JSON plan payload 
    tlsCertSecret: abc.cert
    errorMessageTemplate: "Message: {{ .message }}"
  - stage: post-planning
    url: https://def.xyz/
    enabled: true
    tlsCertSecret: def.cert
```

I believe that will answer both scenarios of webhook processing.

BTW will it create a `ValidationWebhook` monitoring `Terraform` objects? If so, wouldn't it be more clear to have a generic API: e.g. `TerraformWebhook` (with the ability to extend it to default/modifying webhook and validation stages)
