### ISSUE TITLE
Implement spec.values as a special variable

### ISSUE THREAD

**Issue by chanwit** [weaveworks/tf-controller#366]
`spec.values` would give us a good level of abstraction (something like Crossplane, but better) without having a ton of CRDs.
Together with a newly developed package generator (tofu-jet), we would be allowed to express something like this:
```yaml
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: my-ec2-policy
  namespace: flux-system
spec:
  values:
    name: my-ec2-policy  
    description: "My EC2 policy"
    policy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
                "Effect": "Allow",
                "Action": [
                    "ec2:*",
                ],
                "Resource": "*"
          }
        ]
      }
  path: ./aws_iam_policy
  sourceRef:
    kind: OCIRepository
    name: aws-primitive-modules-v4.32.0
```

Flux OCIRepository would become our packaging system to deliver this new kind of modules.
We would also be able to support AWS primitive modules out of the box.
