### ISSUE TITLE
Change template delimiters

### ISSUE THREAD

**Issue by chanwit** [weaveworks/tf-controller#417]
The current Helm-like delimiters like this `{{ .value }}`cause a problem to YAML. They prevent a Terraform object from referring to some types of values, like bool, and number.

```yaml
spec:
  values:
    my_number: "{{ .num }}" # it is rendered as "1", with quotes.
    true_or_false: "{{ .ref }}" # it is rendered as "true" or "false" with quotes.
```

if we change the delimiters to be GitHub Action-like syntax `${{ .ref }}`, it would allow us to render template correctly.
like this:

```yaml
spec:
  values:
    my_number: ${{ .num }} # it is rendered as 1, without quotes.
    true_or_false: ${{ .ref }} # it is rendered as true or false without quotes.
```
