### ISSUE TITLE
`valueFrom` in `.spec.vars` isn't working

### ISSUE THREAD

**Issue by tomhuang12** [weaveworks/tf-controller#457]
I can't find any code that really takes them into account. Since we have `varsFrom`, we can consider removing it.

I do see a potential use case where the ConfigMap/Secret has a different key from the terraform variable name, and `varsFrom` is not able to handle this case.

```
# variables.tf
variable "var1" {
  type = string
}
```
```
# configmap.yaml
...
metadata:
  name: my-configmap
data:
  some-other-key: value
...
```
```
# terraform.yaml
...
spec:
  vars:
  - name: var1
     valueFrom:
       configMapKeyRef:
         name:  my-configmap
         key: some-other-key
```

**Comment by chanwit** [comment]
Thank you so much @tomhuang12 for bringing this up

Here's the steps we would do:
- we mark this feature as deprecated by saying it in the CRD schema.
- we'll remove this in v1beta1 (not v1alpha2)

would we need to find a way to workaround this variable mapping behavior?
It's still likely to be needed per your suggestion.

**Comment by tomhuang12** [comment]
I ran into this actually. I think we need a way to have this variable mapping so that I don't need to create a secret/ConfigMap of matching names just for this case.

**Comment by o-orand** [comment]
Hello, I also ran into this, in  0.13.1. I've checked quickly in `https://github.com/weaveworks/tf-controller/releases/download/v0.14.0-rc.5/tf-controller.crds.yaml`, and it seems not mark as `deprecated`.

**Comment by o-orand** [comment]
As I wasn't able to use this feature, (neither `varsFrom`) as a workaround, I mount required secrets in tf pod, and use `local` terraform provider to read from local filesystem. 


```
# terraform.yaml
  ...
  runnerPodTemplate:
    spec:
      volumes:
        - name: credentials
          secret:
            secretName: my-generated-secrets
            items:
              - key: password
                path: a-password
              - key: username
                path: a-username
      volumeMounts:
        - name: credentials
          mountPath: "/tmp/credentials/password/value"
          subPath: password
        - name: credentials
          mountPath: "/tmp/credentials/username/value"
          subPath: username
...

```

```
# provider.tf
data local_file "main_password" {
  filename = "/tmp/credentials/password/value"
}
data local_file "main_username" {
  filename = "/tmp/credentials/username/value"
}

provider "my-provider" {
  url      = "https://my-provider.com"
  username = data.local_file.main_username.content
  password = data.local_file.main_password.content
}

```
