### ISSUE TITLE
The runner is not picking the correct Terraform state

### ISSUE THREAD

**Issue by dcfranca** [weaveworks/tf-controller#461]
I have a terraform controller for Flux running with a Github provider, however, it seems to be picking up the wrong Terraform state, so it keeps trying to recreate the resources again and again (and fails because they already exist)

This is how it is configured

```
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: saas-github
  namespace: flux-system
spec:
  interval: 2h
  approvePlan: "auto"
  workspace: "prod"
  backendConfig:
    customConfiguration: |
      backend "s3" {
        bucket                      = "my-bucket"
        key                         = "my-key"
        region                      = "eu-west-1"
        dynamodb_table              = "state-lock"
        role_arn                    = "arn:aws:iam::11111:role/my-role"
        encrypt                     = true
      }
  path: ./terraform/saas/github
  runnerPodTemplate:
    metadata:
      annotations:
        iam.amazonaws.com/role: pod-role
  sourceRef:
    kind: GitRepository
    name: infrastructure
    namespace: flux-system
```

locally running terraform init with a `state.config` file that has a similar/same configuration it works fine and it detect the current state properly:

bucket         = "my-bucket"
key            = "infrastructure-github"
region         = "eu-west-1"
dynamodb_table = "state-lock"
role_arn       = "arn:aws:iam::111111:role/my-role"
encrypt        = true

Reading the documentation I saw also a `configPath` that could be used, so I tried to point it to the state file, but then I got the error: 
`Failed to initialize kubernetes configuration: error loading config file couldn't get version/kind; json parse error`

Which is weird, like it tries to load Kuberntes configuration, not Terraform, or at least it expects a json file, which is not the case of my state configuration

I'm running Terraform 1.3.1 on both locally and on the tf runner pod

On the runner pod I can see the `generated_backend_config.tf` and it is the same configuration and `.terraform/terraform.tfstate` also points to the bucket

The only suspicious thing on the logs that I could find is this:

```
- Finding latest version of hashicorp/github...
- Finding integrations/github versions matching "~> 4.0"...
- Finding latest version of hashicorp/aws...
- Installing hashicorp/github v5.9.1...
- Installed hashicorp/github v5.9.1 (signed by HashiCorp)
- Installing integrations/github v4.31.0...
- Installed integrations/github v4.31.0 (signed by a HashiCorp partner, key ID 38027F80D7FD5FB2)
- Installing hashicorp/aws v4.41.0...
- Installed hashicorp/aws v4.41.0 (signed by HashiCorp)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.


Warning: Additional provider information from registry

The remote registry returned warnings for
registry.terraform.io/hashicorp/github:
- For users on Terraform 0.13 or greater, this provider has moved to
integrations/github. Please update your source in required_providers.
```
It seems that it installs 2 github providers, one from hashicorp and one from integrations... I have changed versions of Terraform/provider during the development, and I have removed any reference to the hashicorp one, but this warning still happens

However, it also happens locally, where it reads the correct state, so I don't think it is related.

**Comment by chanwit** [comment]
> so it keeps trying to recreate the resources again and again (and fails because they already exist)

I guessed this was a problem of the GitHub provider, as I was once hit by this behavior too.
Could you please fix your state manually by running `terraform import` and see if the problem goes away?

**Comment by dcfranca** [comment]
@chanwit It is hundreds of resources :'( 
And for that I would need to run the imports on the `tf-runner` pod, right? Because if I run it locally it works fine

**Comment by chanwit** [comment]
Unlike other providers e.g AWS, it seems to me that the GitHub TF provider does not support Terraform's drift detection. Probably, you have to disable drift detection for a certain sets of your resources.

See here:
https://weaveworks.github.io/tf-controller/use_tf_controller/with_drift_detection_disabled/

**Comment by dcfranca** [comment]
I have disabled it, the same issue still happens

**Comment by chanwit** [comment]
So they're not related then.


Btw, you are safe to put `.terraform.lock.hcl` file into your GitOps repo. TF-controller will also pick it up. It might help resolve your problem.

**Comment by dcfranca** [comment]
Added, still the same issue... it tries to add all resources:
```
Plan: 381 to add, 0 to change, 0 to destroy.
```

**Comment by chanwit** [comment]
Here's my next guess, did you happen to set any workspace?

**Comment by dcfranca** [comment]
no, it tries to run on the `default` namespace

**Comment by chanwit** [comment]
No I meant the Terraform `workspace="prod"`, not the Kubernetes namespace.
Did it work without setting the workspace?

**Comment by dcfranca** [comment]
No, when I remove the `workspace="prod"` it tries to provision `default`, and it fails to even plan as our resources are coupled to the workspace in some ways.

When `workspace="prod"` is in place it tries to recreate everything

**Comment by chanwit** [comment]
I have no clue atm.
I'll find some free time to setup an environment that replicates yours to track this bug down.

Not to promise, but I should find some free slots next week.

**Comment by chanwit** [comment]
ping @phoban01 @tomhuang12 @Nalum in case you have tried workspace + S3 backend similar to this setup?

**Comment by k0da** [comment]
I'm running workspace with s3 without issues. Though I specified empty backend config, then supply it with secret. I can paste snippet later if you want

**Comment by chanwit** [comment]
That would be great!
@k0da was the one who implemented most of workspace-related codes. 

@dcfranca would it be possible for you to try a small set of resources on a different region first to see how it behaves?

**Comment by Nalum** [comment]
Unfortunately I haven't used workspaces with this yet.

**Comment by k0da** [comment]
```yaml
  workspace: nonprod-bcp-tools
  backendConfig:
    customConfiguration: "backend \"s3\"{}"
  backendConfigsFrom:
  - kind: ConfigMap
    name: nonprod-backend
```
