### ISSUE TITLE
Webhook available when backendConfig.disable: true

### ISSUE THREAD

**Issue by odise** [weaveworks/tf-controller#468]
Hi guys,

I try to configure post-planning webhook however hitting error message:

```
failed to prepare webhook payload: failed to get plan file: rpc error:
code = Unknown desc = \nError: Failed to read the given file as a state or plan
file\n\nState read error: Error loading statefile: open tfplan: no such file
or\ndirectory\n\nPlan read error: open tfplan: no such file or directory\n"
```

Here a little bit of log output facilitating the error above:

```
{"level":"info","ts":"2022-12-01T13:26:04.272Z","msg":"calling post planning webhooks ...","controller":"terraform","controllerGroup":"infra.contrib.fluxcd.io","controllerKind":"Terraform","Terraform":{"name":"feature-flag-alpha-lqt-playground","namespace":"flux-system"},"namespace":"flux-system","name":"feature-flag-alpha-lqt-playground","reconcileID":"795cea8d-89f3-4fc9-9ac5-127e0c04399d","reconciliation-loop-id":"a1346848-9fdb-46b4-8b59-e1377d63489b","start-time":"2022-12-01T13:25:28.749Z"}
{"level":"info","ts":"2022-12-01T13:26:04.272Z","msg":"processing post-planning webhook","controller":"terraform","controllerGroup":"infra.contrib.fluxcd.io","controllerKind":"Terraform","Terraform":{"name":"feature-flag-alpha-lqt-playground","namespace":"flux-system"},"namespace":"flux-system","name":"feature-flag-alpha-lqt-playground","reconcileID":"795cea8d-89f3-4fc9-9ac5-127e0c04399d","reconciliation-loop-id":"a1346848-9fdb-46b4-8b59-e1377d63489b","start-time":"2022-12-01T13:25:28.749Z","webhook":"http://webhook/webhook"}
{"level":"info","ts":"2022-12-01T13:26:04.272Z","msg":"webhook is enabled, processing","controller":"terraform","controllerGroup":"infra.contrib.fluxcd.io","controllerKind":"Terraform","Terraform":{"name":"feature-flag-alpha-lqt-playground","namespace":"flux-system"},"namespace":"flux-system","name":"feature-flag-alpha-lqt-playground","reconcileID":"795cea8d-89f3-4fc9-9ac5-127e0c04399d","reconciliation-loop-id":"a1346848-9fdb-46b4-8b59-e1377d63489b","start-time":"2022-12-01T13:25:28.749Z"}
{"level":"error","ts":"2022-12-01T13:26:04.306Z","msg":"failed during the process of post planning webhooks","controller":"terraform","controllerGroup":"infra.contrib.fluxcd.io","controllerKind":"Terraform","Terraform":{"name":"feature-flag-alpha-lqt-playground","namespace":"flux-system"},"namespace":"flux-system","name":"feature-flag-alpha-lqt-playground","reconcileID":"795cea8d-89f3-4fc9-9ac5-127e0c04399d","reconciliation-loop-id":"a1346848-9fdb-46b4-8b59-e1377d63489b","start-time":"2022-12-01T13:25:28.749Z","error":"failed to prepare webhook payload: failed to get plan file: rpc error: code = Unknown desc = \nError: Failed to read the given file as a state or plan file\n\nState read error: Error loading statefile: open tfplan: no such file or\ndirectory\n\nPlan read error: open tfplan: no such file or directory\n"}
{"level":"error","ts":"2022-12-01T13:26:04.306Z","msg":"error planning","controller":"terraform","controllerGroup":"infra.contrib.fluxcd.io","controllerKind":"Terraform","Terraform":{"name":"feature-flag-alpha-lqt-playground","namespace":"flux-system"},"namespace":"flux-system","name":"feature-flag-alpha-lqt-playground","reconcileID":"795cea8d-89f3-4fc9-9ac5-127e0c04399d","reconciliation-loop-id":"a1346848-9fdb-46b4-8b59-e1377d63489b","start-time":"2022-12-01T13:25:28.749Z","error":"failed to prepare webhook payload: failed to get plan file: rpc error: code = Unknown desc = \nError: Failed to read the given file as a state or plan file\n\nState read error: Error loading statefile: open tfplan: no such file or\ndirectory\n\nPlan read error: open tfplan: no such file or directory\n"}
{"level":"error","ts":"2022-12-01T13:26:04.358Z","msg":"Reconciliation failed after 35.608963736s, next try in 15m0s","controller":"terraform","controllerGroup":"infra.contrib.fluxcd.io","controllerKind":"Terraform","Terraform":{"name":"feature-flag-alpha-lqt-playground","namespace":"flux-system"},"namespace":"flux-system","name":"feature-flag-alpha-lqt-playground","reconcileID":"795cea8d-89f3-4fc9-9ac5-127e0c04399d","reconciliation-loop-id":"a1346848-9fdb-46b4-8b59-e1377d63489b","start-time":"2022-12-01T13:25:28.749Z","revision":"main/83589bb129ca74a0c8f3ea05931fddbd61289404","error":"failed to prepare webhook payload: failed to get plan file: rpc error: code = Unknown desc = \nError: Failed to read the given file as a state or plan file\n\nState read error: Error loading statefile: open tfplan: no such file or\ndirectory\n\nPlan read error: open tfplan: no such file or directory\n"}
```

Here is my Terraform yaml:

```
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: feature-flag-alpha-lqt-playground
  namespace: flux-system
spec:
  alwaysCleanupRunnerPod: false
  approvePlan: auto
  backendConfig:
    disable: true
  destroyResourcesOnDeletion: false
  disableDriftDetection: false
  force: false
  interval: 15m
  path: playground-alpha/terraform/services/feature-flag
  refreshBeforeApply: false
  runnerTerminationGracePeriodSeconds: 30
  serviceAccountName: tf-runner
  sourceRef:
    kind: GitRepository
    name: feature-flag-alpha-lqt-playground
    namespace: flux-system
  storeReadablePlan: none
  webhooks:
  - enabled: true
    errorMessageTemplate: 'Violation: {{ (index .violations 0).message }}'
    payloadType: SpecAndPlan
    stage: post-planning
    url: http://webhook/webhook
  workspace: default
```

Digging around in the code I stumbled upon https://github.com/weaveworks/tf-controller/blob/850c5aee1f6fcb6e07155db95743ca25b2204f0b/controllers/tf_controller_plan.go#L51 which seems to prevent the runner from storing any kind of plan file in case the backend config is disabled. 

Is there a way to call post-planning webhooks in combination with external TF backends? Or do I miss something here?
