### ISSUE TITLE
Enable CrossNamespaceReferences for ServiceAccounts

### ISSUE THREAD

**Issue by dfreilich** [weaveworks/tf-controller#473]
Currently, `Terraform` objects contain a reference to a `serviceAccount`, an entity which must be present in order to proceed with the object. 

This reference is currently just a string reference to a `serviceAccount` object in the `Terraform` objects namespace: https://github.com/weaveworks/tf-controller/blob/a4d31bb311e7d405bb9e0d3b357b4bb7766927b5/api/v1alpha1/terraform_types.go#L179-L183

Can this be switched  to a `CrossNamespaceReference`, similar to `SourceRef`? https://github.com/weaveworks/tf-controller/blob/a4d31bb311e7d405bb9e0d3b357b4bb7766927b5/api/v1alpha1/terraform_types.go#L135-L137

In our current use-case, we are creating `Terraform` objects in a number of different namespaces, based on permissions, and to escape this limitation we are creating `serviceAccounts` with the correct `ClusterRoleBinding` in every namespace we create, but ideally I'd like to just point it to the service account that the `TFController` creates, so that we don't have any long-term compatibility issues (if permissions in the `serviceAccount` change). 

What do you think?

**Comment by chanwit** [comment]
Unlike sourceRef, referring to a powerful service account would allow privilege escalation.
So we still have to rely on the namespace boundary principles used by Flux for security reasons.

Multi-tenancy implementation would be easily violated if we allow to do so.

**Comment by tomhuang12** [comment]
If you are using helm to deploy it, you can specify a list of namespaces in values `runner.serviceAccount.allowedNamespaces` to create service accounts in respective namespaces.

**Comment by artem-nefedov** [comment]
This wouldn't be possible anyways, because runner Pod is always started in the same namespace as Terraform resource, and Pod can only use a ServiceAccount from the same namespace.

The feature I would love to see is to be able to start runner Pod in a different namespace.
`runner.serviceAccount.allowedNamespaces` unfortunately doesn't really help in many cases, such as when you want to use IRSA with ServiceAccount created by eksctl, but still want to have Terraform resources in multiple namespaces.

**Comment by tomhuang12** [comment]
@artem-nefedov is this the use case you are talking about?

```
tf-namespace: tf-controller runner pod
ns1: Terraform helloworld1
ns2: Terraform helloworld2

###
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: helloworld1
  namespace: ns1
spec:
  interval: 1m
  path: ./
  targetNamespace: tf-namespace # specify the namespace the runner pod should run in
  sourceRef:
    kind: GitRepository
    name: helloworld
    namespace: flux-system

###
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: helloworld2
  namespace: ns2
spec:
  interval: 1m
  path: ./
  targetNamespace: tf-namespace # specify the namespace the runner pod should run in
  sourceRef:
    kind: GitRepository
    name: helloworld
```

In this case, you would just have a SA in tf-namespace. 

@chanwit I think we can allow this and if hard multi-tenancy is required, users can add policies to enforce it like what Flux's example policies.
