### ISSUE TITLE
Support for complex in templates rendering in values

### ISSUE THREAD

**Issue by akselleirv** [weaveworks/tf-controller#491]
I want to being allowed to use complex structures in the values field from another job's output.

## Example
Given these two modules:
`job-a`:
```
output "my_list" {
  value = [
    "entry-1",
    "entry-2"
  ]
}
```
`job-b`:
```
variable "values" {
  type = object({
    my_list = set(string)
  })
}
```

Where `job-b` uses the output of `job-a` as its variable inputs.

My Terraform CRDs looks like the following:
```
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: job-a
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 10s
  approvePlan: auto
  path: ./modules/job-a
  sourceRef:
    kind: GitRepository
    name: my-repo
    namespace: flux-system
  destroyResourcesOnDeletion: true
  writeOutputsToSecret:
    name: job-a-outputs
    outputs:
      - my_list
---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: job-b
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 10s
  approvePlan: auto
  path: ./modules/job-b
  sourceRef:
    kind: GitRepository
    name: my-repo
    namespace: flux-system
  destroyResourcesOnDeletion: true
  readInputsFromSecrets:
    - name: job-a-outputs
      as: job_a
  dependsOn:
    - name: job-a
  values:
    my_list: ${{ .job_a.my_list }}
```

If I try this now then I get this error: `"logger":"runner.terraform","msg":"unable to marshal the data","instance-id":"ea32bfa5-0d76-4083-8ff4-d71552285c66","error":"json: error calling Marshal JSON for type *v1.JSON: invalid character 'e' after object key:value pair"`

Would it be feasible to add this feature?
