### ISSUE TITLE
Migrate projects managed by terraform

### ISSUE THREAD

**Issue by fabidick22** [weaveworks/tf-controller#524]
I'm trying to migrate projects managed with terraform, and I'm wondering if it is possible to specify tf-controller to use the existing backend configuration? 
I understand that if the backend configuration is not specified, tf-controller uses Kubernetes Backend, and that we can use a custom backend with the `customConfiguration` attribute. Is there a way for tf-controller to work with the backend already configured in the project?

**Comment by k0da** [comment]
yes, we used existing s3 buckets and migrated from github action to tf-controller

**Comment by fabidick22** [comment]
Hi @k0da, how can you archive this? Do you need to specify something in the terraform manifests?
This is my current setup, but for some reason it is using Kubernetes backend by default.
```yaml
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: repo-tf-controller
  namespace: flux-system
spec:
  interval: 4m
  approvePlan: auto
  path: terraform/tf-controller/s3
  sourceRef:
    kind: GitRepository
    name: repo...
    namespace: flux-system
```

**Comment by fabidick22** [comment]
So the backend configs have to be set as a `ConfigMap` resource?
Is there a way to get `tf-controller` to take the configurations from the git repository?
A specific use case is that a work team can update the backend configurations and `tf-controller` can use these same configurations that were edited by the team.

**Comment by chanwit** [comment]
No you don't need to.
Yo can follow @k0da suggestion by
setting:
```
spec:
  backendConfig:
    customConfiguration: "backend \"s3\"{}"
```
and in Git you can have another file say `backend.tf` which contains your S3 backend there,

```hcl
#  backend,tf
backend "s3" {
 ...
}
```
and everything would work for you.

**Comment by fabidick22** [comment]
Thanks guys @chanwit, @k0da 

for some reason, I'm getting this error:
![image](https://user-images.githubusercontent.com/8176821/218767591-c64b1f05-1644-41cb-a42d-76216e81c9b2.png)

This is the directory of my terraform project, I have applied `apply` and `destroy` from the Terraform CLI to rule out any config error in the backend and everything works correctly:
![image](https://user-images.githubusercontent.com/8176821/218769036-377af051-f522-4048-923c-e46aa64de972.png)


This is my terraform manifest config, if I remove the `backendConfig` attribute everything works fine, but it uses the Kubernetes backend.
```yaml
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: platform-infra-tf-controller
  namespace: flux-system
spec:
  interval: 4m
  approvePlan: auto
  path: terraform/tf-controller/s3
  backendConfig:
    customConfiguration: "backend \"s3\"{}"
  sourceRef:
    kind: GitRepository
    name: repo
    namespace: flux-system
```

This is my manifest to install tf-controller:

<details><summary>tf-controller.yml</summary>

```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  interval: 2h0s
  url: https://weaveworks.github.io/tf-controller/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  chart:
    spec:
      chart: tf-controller
      sourceRef:
        kind: HelmRepository
        name: tf-controller
      version: '>=0.9.3'
  interval: 2h0s
  releaseName: tf-controller
  targetNamespace: flux-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    replicaCount: 1
    concurrency: 24
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 400m
        memory: 64Mi
    caCertValidityDuration: 24h
    certRotationCheckFrequency: 30m
    image:
      tag: v0.13.1
    runner:
      serviceAccount:
        annotations:
          eks.amazonaws.com/role-arn: ...
      image:
        tag: v0.13.1
    awsPackage:
      install: true
      tag: v4.38.0-v1alpha11
```
</details>

Any idea what I'm doing wrong?
