### ISSUE TITLE
TF Runner Acknowledges Workspace Exists But Doesn't Select

### ISSUE THREAD

**Issue by shin-go** [weaveworks/tf-controller#542]
helm chart version: v0.11.0
controller version: v0.14.0
Kubernetes platform/version: AWS EKS 1.23.13
Terraform (client) version: 1.0.0+

**Issue Description:**

I'm trying to evaluate the tf-controller in a drift detection only capacity and have encountered behavior where when setting a custom configuration for backend (remote S3 bucket), the runner will acknowledge the configured workspace exists but rather than selecting it and proceeding to produce a plan, the runner bails out and terminates. The `terraform` CR is left in a perpetual "initializing..." state and produces no events.

**Expected Behavior:**

I could have things misconfigured, but I was expecting that a plan be produced that is captured in the runner's event logs. Since this is just a "kick the tires" basic exercise I'm not thinking things like using the notification-controller to post to a Slack channel, etc. but I wouldn't be surprised they're actually going to the notification-controller due to the `values.eventsAddress` config. 

However, what looks off to me is that the `terraform` CR gets stuck in a perpetual "Initializing" state and no events are produced relating to the CR that indicate misbehavior which makes this hard to interpret as expected behavior or not.

**Additional Information:**

Here's a sample of the `terraform` CR being used with sensitive info obfuscated as applied to the EKS cluster to test. I've omitted the `gitRepository` CR, but I can assure you it's configured correctly:
```
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: some-app
  namespace: flux-system
spec:
  path: ./some-app
  interval: 1h
  approvePlan: disable
  backendConfig:
    customConfiguration: |
      backend "s3" {
        bucket = "tf-remote-state"
        key = "some-app.tfstate"
        region = "us-west-2"
        skip_credentials_validation = true
        skip_metadata_api_check = true
        force_path_style = true
        encrypt = true
      }
  sourceRef:
    kind: GitRepository
    name: terraform-repo
  workspace: dev
```
The tf-controller was laid down via the Helm chart on the noted version above like so:
```
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  interval: 8h
  url: https://weaveworks.github.io/tf-controller/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  interval: 12h
  releaseName: tf-controller
  chart:
    spec:
      chart: tf-controller
      version: "0.11.0"
      sourceRef:
        kind: HelmRepository
        name: tf-controller
        namespace: flux-system
      interval: 1h
  values:
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 10m
        memory: 32Mi
    logEncoding: console
    eventsAddress: http://notification-controller.flux-system.svc.cluster.local./
    runner:
      allowedNamespaces: ['*']
      serviceAccount:
        annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::11111111111:role/flux-tf-role
```

One thing I will note that might be unusual is the remote S3 bucket is *not on the same* AWS account as the EKS cluster and associated IAM Role for IRSA is homed. A bucket policy was implemented to allow the obfuscated annotated IAM Role access as a Principal, which seems to be valid as the runner event logs produce the following output when attempting to reconcile the CR:
```
2023/02/27 20:00:44 Starting the runner... version  sha 
I0227 20:00:45.966971       6 request.go:690] Waited for 1.033815115s due to client-side throttling, not priority and fairness, request: GET:https://172.20.0.1:443/apis/node.k8s.io/v1beta1?timeout=32s
{"level":"info","ts":"2023-02-27T20:00:59.164Z","logger":"runner.terraform","msg":"preparing for Upload and Extraction","instance-id":""}
{"level":"info","ts":"2023-02-27T20:00:59.248Z","logger":"runner.terraform","msg":"write backend config","instance-id":"","path":"/tmp/flux-system-some-app/some-app","config":"backend_override.tf"}
{"level":"info","ts":"2023-02-27T20:00:59.249Z","logger":"runner.terraform","msg":"write config to file","instance-id":"","filePath":"/tmp/flux-system-some-app/some-app/backend_override.tf"}
{"level":"info","ts":"2023-02-27T20:00:59.251Z","logger":"runner.terraform","msg":"looking for path","instance-id":"","file":"terraform"}
{"level":"info","ts":"2023-02-27T20:00:59.252Z","logger":"runner.terraform","msg":"creating new terraform","instance-id":"29d7439d-e6cc-4184-a488-c97694462a98","workingDir":"/tmp/flux-system-some-app/some-app","execPath":"/usr/local/bin/terraform"}
{"level":"info","ts":"2023-02-27T20:00:59.256Z","logger":"runner.terraform","msg":"setting envvars","instance-id":"29d7439d-e6cc-4184-a488-c97694462a98"}
{"level":"info","ts":"2023-02-27T20:00:59.256Z","logger":"runner.terraform","msg":"getting envvars from os environments","instance-id":"29d7439d-e6cc-4184-a488-c97694462a98"}
{"level":"info","ts":"2023-02-27T20:00:59.257Z","logger":"runner.terraform","msg":"setting up the input variables","instance-id":"29d7439d-e6cc-4184-a488-c97694462a98"}
{"level":"info","ts":"2023-02-27T20:00:59.258Z","logger":"runner.terraform","msg":"mapping the Spec.Values","instance-id":"29d7439d-e6cc-4184-a488-c97694462a98"}
{"level":"info","ts":"2023-02-27T20:00:59.258Z","logger":"runner.terraform","msg":"mapping the Spec.Vars","instance-id":"29d7439d-e6cc-4184-a488-c97694462a98"}
{"level":"info","ts":"2023-02-27T20:00:59.258Z","logger":"runner.terraform","msg":"mapping the Spec.VarsFrom","instance-id":"29d7439d-e6cc-4184-a488-c97694462a98"}
{"level":"info","ts":"2023-02-27T20:00:59.259Z","logger":"runner.terraform","msg":"generating the template founds"}
{"level":"info","ts":"2023-02-27T20:00:59.259Z","logger":"runner.terraform","msg":"main.tf.tpl not found, skipping"}
{"level":"info","ts":"2023-02-27T20:00:59.260Z","logger":"runner.terraform","msg":"initializing","instance-id":"29d7439d-e6cc-4184-a488-c97694462a98"}
{"level":"info","ts":"2023-02-27T20:00:59.260Z","logger":"runner.terraform","msg":"mapping the Spec.BackendConfigsFrom","instance-id":"29d7439d-e6cc-4184-a488-c97694462a98"}
{
  "terraform_version": "1.3.9",
  "platform": "linux_amd64",
  "provider_selections": {},
  "terraform_outdated": false
}
Upgrading modules...
- cpu-usage-alert-clarolab-svc in ../newrelic/modules/alerts/generic-nrql-alert-condition
- db-span-alert-clarolab-svc in ../newrelic/modules/alerts/generic-nrql-alert-condition
... and so on for modules ...

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- terraform.io/builtin/terraform is built in to Terraform
- Finding newrelic/newrelic versions matching "~> 2.41, ~> 2.48"...
- Finding hashicorp/aws versions matching "~> 4.5"...
- Installing newrelic/newrelic v2.50.2...
- Installed newrelic/newrelic v2.50.2 (signed by a HashiCorp partner, key ID DC9FC6B1FCE47986)
- Installing hashicorp/aws v4.56.0...
- Installed hashicorp/aws v4.56.0 (signed by HashiCorp)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!
{"level":"info","ts":"2023-02-27T20:01:08.045Z","logger":"runner.terraform","msg":"workspace select"}
Workspace "dev" already exists
{"level":"info","ts":"2023-02-27T20:01:09.899Z","logger":"runner.terraform","msg":"workspace new:, workspace \"dev\" already exists"}
Switched to workspace "dev".
{"level":"info","ts":"2023-02-27T20:01:11.889Z","logger":"runner.terraform","msg":"cleanup TmpDir","instance-id":"29d7439d-e6cc-4184-a488-c97694462a98","tmpDir":"/tmp/flux-system-some-app"}
```
So as you can see from the event logs near the end before the runner terminates that the workspace is apparently set to `dev` as set in the CR.

Aside from the `terraform` CR config and behavior, I was recommended to base config off of https://weaveworks.github.io/tf-controller/use_tf_controller/with_a_custom_backend/. However, I find it peculiar that tf-controller can't look for the `backend "s3" {}` block within the `terraform {}` block found in someplace like `main.tf`. Having to specify it explicitly in the CR seems redundant if already present in the codebase being cloned for the `sourceRef` of the `terraform` CR. I'm happy to address this in a separate issue.
