### ISSUE TITLE
Issues with GCS and backendConfigsFrom

### ISSUE THREAD

**Issue by mcortinas** [weaveworks/tf-controller#543]
Hello,

 I'm trying to use `backendConfigsFrom`  in order to use the properly google service account to read / write the terraform state in a GCS bucket. 

 I read this elegant solution from this https://github.com/weaveworks/tf-controller/issues/389 

 I have some issues and the runner doesn't help me and I don't know how can open more the logging of  runner in order to detect what i'm doing wrong....

 Let me share my Terraform yaml code....
 ```apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: poc
spec:
  sourceRef:
    kind: OCIRepository
    name: fastlycomputeatedge
  backendConfig:
    customConfiguration: "backend \"gcs\"{}"
  backendConfigsFrom:
  - kind: Secret
    name: gcp-credentials-lab
```
 Let me share my Secret yaml code....
```
apiVersion: v1
kind: Secret
metadata:
  name: gcp-credentials-lab
  namespace: flux-system
data:
  bucket: ZWRvLXRmc3RhdGUtbGFiLXNlcnZpY2VzCg==
  prefix: Y2RuL2NvbXB1dGVhdGVkZ2UK
  credentials: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiA.....
```

The error trace is 
```
Error: Failed to get existing workspaces: querying Cloud Storage failed: storage: bucket doesn't exist
```

I checked base64 and it seems fine
```
$echo ZWRvLXRmc3RhdGUtbGFiLXNlcnZpY2VzCg== | base64 -d
edo-tfstate-lab-services
$echo Y2RuL2NvbXB1dGVhdGVkZ2UK | base64 -d 
cdn/computeatedge
```

The bucket created in GCS is
```
gs://edo-tfstate-lab-services/cdn/computeatedge/default.tfstate
```

I should enable access log in GCS in order to analyze  what is hitting, but It helps to me some way to adding debug logs ...
