### ISSUE TITLE
Type information in outputs broke flux Kustomization variable substitution

### ISSUE THREAD

**Issue by artem-nefedov** [weaveworks/tf-controller#545]
We were using outputs of tf-runner in flux Kustomizations as a source for [variable substitution](https://fluxcd.io/flux/components/kustomize/kustomization/#variable-substitution), like so:

```yaml
spec:
  postBuild:
    substitureFrom:
    - kind: Secret
      name: foo
```

However, this workflow is broken after upgrade to tf-controller 0.14.0 due to this change: https://github.com/weaveworks/tf-controller/commit/1583733bb6e3e0de3f4bc933215a838a63ef80cf
Reason being is that kustomize-controller freaks out when it sees variables with `.` in the name (even if those specific variables aren't used for substitution).

Is there any way to disable this functionality?
