### ISSUE TITLE
Proposal: Support idempotent "create or update" behavior (optional import)

### ISSUE THREAD

**Issue by artem-nefedov** [weaveworks/tf-controller#553]
## Introduction

One thing that is great in Crossplane, and also something I miss with tf-controller, is ability to idempotently apply resources regardless of whether they already exist or not.

Thoughts/comments are welcome.

## How it works in Crossplane

Assuming the cloud resource allows specifying the exact name (meaning the name isn't something like randomly-generated ID), you can set `crossplane.io/external-name` annotation on custom resource in cluster (without annotation, cloud resource name can also be based on `metadata.name`).

- If cloud resource with such name does not exist, Crossplane will create it.
- If cloud resource with such name does exist, Crossplane will pick it up start managing it as its own (apply changes if configuration differs; do nothing otherwise).

## How this can be emulated in tf-controller

The idea is to overcome Terraform limitations of requiring manual import of existing resources, and make it an idempotent "apply" operation. It would be fine if users have to tell controller what to expect explicitly, as long as **it can be done declaratively and no manual intervention is needed at any point**. I think something like this can be implemented:

Support a map of "imports" in Terraform resource, where key is path in tfstate, and value is the name of resource in cloud. E.g.:

```yaml
spec:
  imports:
    aws_cloudwatch_log_group.cluster: /aws/eks/my-cluster-name/cluster
    module.foo.bar.baz: abcd
    ...
```

..or as a list (to preserve order):

```yaml
spec:
  imports:
  - key: aws_cloudwatch_log_group.cluster
    value: /aws/eks/my-cluster-name/cluster
  - key: module.foo.bar.baz
    value: abcd
  ...
```

For each key-value pair, run `terraform import` command when tf-runner starts and state is initialized. E.g.:

```bash
 terraform import -var-file tfvars.json aws_cloudwatch_log_group.cluster /aws/eks/my-cluster-name/cluster
```

However, **do not fail** the run if import fails because resource doesn't exist. So, if resource exists, we will import it into state, and if it doesn't exist, or is already in the state,  nothing will happen. After that, `terraform apply` will do its job as usual.
