### ISSUE TITLE
Move towards Flux v2 GA

### ISSUE THREAD

**Issue by chanwit** [weaveworks/tf-controller#557]
- [x] Ensure compatibility with Source v1 and Artifact digest
- [x] Verify blob pulling and pushing mechanism
- [ ] Check the impact of changes from Artifact Digest on the planning process

**Comment by klauserber** [comment]
Hi, is this the reason why I am getting this error with Flux v2 v2.0.0-rc.1?

failed to verify artifact: computed checksum '58771dfcb77e839c07029ff76d526aff704d26a9ca1028709f4dc1b4de7f8353' doesn't match advertised ''

**Comment by chanwit** [comment]
Yes, that's correct @klauserber 

It's a big breaking change for TF Controller. Many parts to be fixed.
So please stay tuned.

**Comment by onedr0p** [comment]
I am also facing this issue after updating to Flux v2.0.0-rc.1 good to know you are on it. Thanks!

**Comment by chanwit** [comment]
@klauserber @onedr0p the PR is upped, and we have the image from the PR in case you'd like to try it:

```
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  interval: 1h0s
  url: https://weaveworks.github.io/tf-controller/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  chart:
    spec:
      chart: tf-controller
      sourceRef:
        kind: HelmRepository
        name: tf-controller
      version: '>=0.11.0'
  interval: 1h0s
  releaseName: tf-controller
  targetNamespace: flux-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    replicaCount: 1
    concurrency: 24
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 400m
        memory: 64Mi
    caCertValidityDuration: 24h
    certRotationCheckFrequency: 30m
    image:
      tag: upgrade-to-flux-2-rc-1-634c26bf
    runner:
      image:
        tag: upgrade-to-flux-2-rc-1-634c26bf
```
