### ISSUE TITLE
Does tf-controller support workload identity for Azure?

### ISSUE THREAD

**Issue by masashi-noguchi** [weaveworks/tf-controller#561]
Does Terraform Controller  support workload identity for Azure?(see https://github.com/Azure/azure-workload-identity)

After helmrelease the terraform controller to Azure, when I deploy the Terraform resource, I get the following authentication error in tf-runner pod.
Appropriate Azure Managed ID privileges are granted to the workload identity for the serviceaccount, so if Terraform Controller supports it, an authentication error should not occur, but is it not currently supported?

```
❯ kubectl get pod tf-runner -o yaml
    message: |+
      error running Init: rpc error: code = Internal desc = exit status 1

      Error: Failed to get existing workspaces: Error retrieving keys for Storage Account "<storageaccount>": azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/<subscriptionid>/resourceGroups/<resourceGroups>/providers/Microsoft.Storage/storageAccounts/<storageaccount>/listKeys?api-version=2021-01-01: StatusCode=404 -- Original Error: adal: Refresh request failed. Status Code = '404'. Response body: getting assigned identities for pod <namespace>/tf-runner in CREATED state failed after 16 attempts, retry duration [5]s, error: <nil>. Check MIC pod logs for identity assignment errors
       Endpoint http://xxx.xxx.xxx.xxx/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fmanagement.azure.com%2F
```

**Comment by k0da** [comment]
it looks like a Terraform error. To me it seem like backend isn't configured properly

**Comment by masashi-noguchi** [comment]
Thank you immediately answer. When I tried the method using this inject sidecar, I was able to set it to the backend.
(see https://learn.microsoft.com/en-us/azure/aks/workload-identity-migrate-from-pod-identity?source=recommendations#deploy-the-workload-with-migration-sidecar)
```
kind: Terraform
spec:
  runnerPodTemplate:
    metadata:
      annotations:
        azure.workload.identity/inject-proxy-sidecar: "true"
    spec:
      env:
      - name: ARM_CLIENT_ID
        value: <client_id of MID>
```
In the above, since the authentication error has disappeared, it seems that the cause is not the backend setting, but the azure workload identity is not supported. 

If you have a successful track record of azure workload identity, I would be happy if you could let me know.

**Comment by maciekdude** [comment]
It does. I have tf-controller running on AKS with workload identity with no problem.
The trick is to use the OIDC flag and explicitly point to the token. 
BTW there's a bug in azurerm 3.44.x. Hence, use anything 3.47 onwards.
Some additional info here https://github.com/hashicorp/terraform-provider-azurerm/issues/20671
Some examples are below. Hope that helps.

Env variables that should be set on the runner pod.
```yaml
       - name: ARM_USE_OIDC
          value: "true"
        - name: ARM_OIDC_TOKEN_FILE_PATH
          value: "/var/run/secrets/azure/tokens/azure-identity-token"
```

Example yaml:

```yaml
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: terraformhello
  namespace: default
spec:
  tfstate:
    forceUnlock: auto
  backendConfig:
    customConfiguration: |
      backend "azurerm" {
        resource_group_name  = "l"
        storage_account_name = ""
        container_name       = "tfstate"
        key                  = "helloworld.tfstate"
        use_oidc             = true
      }
  interval: 1m
  serviceAccountName: service_account_registered_in_aad
  approvePlan: auto
  destroy: true
  path: ./tests/fixture
  sourceRef:
    kind: GitRepository
    name: terraformhello
    namespace: flux-system
  runnerPodTemplate:
    spec:
      image: azure_cli_runner.xxx
      env:
        - name: ARM_USE_OIDC
          value: "true"
        - name: ARM_SUBSCRIPTION_ID
          value: ""
        - name: ARM_TENANT_ID
          value: ""
        - name: ARM_CLIENT_ID
          value: ""
        - name: ARM_OIDC_TOKEN_FILE_PATH
          value: "/var/run/secrets/azure/tokens/azure-identity-token"
```
