### ISSUE TITLE
NetworkPolicy allowing ingress from flux-system namespace still blocks connections to runner pods

### ISSUE THREAD

**Issue by aristapimenta** [weaveworks/tf-controller#563]
Hi,

We have strict `NetworkPolicies` here and I have this one for my `tf-clusters` namespace, which I allowed in the tf-controller Helm chart via `spec.values.runner.serviceAccount.allowedNamespaces`:

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: infra-configs
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: base-policy
  namespace: tf-clusters
spec:
  ingress:
  - from:
    - podSelector: {}
    - namespaceSelector:
        matchLabels:
          kubernetes.io/namespace: monitoring
    - namespaceSelector:
        matchLabels:
          kubernetes.io/namespace: internal-proxy
    - namespaceSelector:
        matchLabels:
          kubernetes.io/namespace: flux-system
  podSelector: {}
  policyTypes:
  - Ingress
```

This policy still blocks tf-controller running in the `flux-system` namespace from dialing to the runner pods. I know that because I see timeouts:

```json
{"level":"error","ts":"2023-04-03T15:58:02.287Z","msg":"Hit an error","controller":"terraform","controllerGroup":"infra.contrib.fluxcd.io","controllerKind":"Terraform","Terraform":{"name":"cv-infra","namespace":"tf-clusters"},"namespace":"tf-clusters","name":"cv-infra","reconcileID":"3525aa72-3f03-4be3-91fb-f914b4fa0b61","reconciliation-loop-id":"5653421f-39f6-4697-b971-c15a934852e7","start-time":"2023-04-03T15:57:17.285Z","function":"TerraformReconciler.lookupOrCreateRunner_000","error":"context deadline exceeded"}
{"level":"error","ts":"2023-04-03T15:58:02.287Z","msg":"unable to lookup or create runner","controller":"terraform","controllerGroup":"infra.contrib.fluxcd.io","controllerKind":"Terraform","Terraform":{"name":"cv-infra","namespace":"tf-clusters"},"namespace":"tf-clusters","name":"cv-infra","reconcileID":"3525aa72-3f03-4be3-91fb-f914b4fa0b61","reconciliation-loop-id":"5653421f-39f6-4697-b971-c15a934852e7","start-time":"2023-04-03T15:57:17.285Z","error":"context deadline exceeded"}
{"level":"error","ts":"2023-04-03T15:58:02.287Z","msg":"Reconciler error","controller":"terraform","controllerGroup":"infra.contrib.fluxcd.io","controllerKind":"Terraform","Terraform":{"name":"cv-infra","namespace":"tf-clusters"},"namespace":"tf-clusters","name":"cv-infra","reconcileID":"3525aa72-3f03-4be3-91fb-f914b4fa0b61","error":"context deadline exceeded"}
```

And also because when I delete the `NetworkPolicy` the reconciliation runs just fine.

How should I configure my `NetworkPolicy` to properly allow the traffic?

Thanks in advance!

**Comment by chanwit** [comment]
Could you also try this and give use feedback please:

```
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-grpc-to-runners
  namespace: infra-ns
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: tf-runner
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              app: flux-system
      ports:
        - protocol: TCP
          port: 30000
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-tf-to-sc-and-nc
  namespace: flux-system
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: tf-controller
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: source-controller
    ports:
    - protocol: TCP
      port: 80
  - from:
    - podSelector:
        matchLabels:
          app: notification-controller
    ports:
    - protocol: TCP
      port: 80
```
