### ISSUE TITLE
Failed to verify artifact

### ISSUE THREAD

**Issue by scott-david-walker** [weaveworks/tf-controller#567]
I'm getting this error when trying to run Terraform. What I find weird is that the advertised checksum is empty?

{"level":"error","ts":"2023-04-12T12:07:51.287Z","msg":"Reconciliation failed after 15.100762353s, next try in 1m0s","controller":"terraform","controllerGroup":"infra.contrib.fluxcd.io","controllerKind":"Terraform","Terraform":{"name":"scott-test2","namespace":"flux-system"},"namespace":"flux-system","name":"scott-test2","reconcileID":"3da98bbc-b9d7-4b1c-a7c2-de3209e78be1","reconciliation-loop-id":"72a4cdb3-463b-4960-ab08-5e6c57361ef5","start-time":"2023-04-12T12:07:36.186Z","revision":"main@sha1:17bca68ee797b8ec40ec42d28dbdc092679eb238","error":"failed to verify artifact: computed checksum 'fd544440eb323cf09252a00cb63e6cf195798fec38e9601026f14044e5e35714' doesn't match advertised ''"}

My file looks  like:

```yaml
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: scott-test2
  namespace: flux-system
spec:
  path: ./terraforms/fusionauth
  interval: 1m
  approvePlan: auto
  sourceRef:
    kind: GitRepository
    name: scott-fake-repo
    namespace: flux-system
```

Git repository is correctly instantiated and has a status of "stored artifact for revision main" so it appears to have the data necessary
