### ISSUE TITLE
Add labels and annotations to outputted secrets

### ISSUE THREAD

**Issue by scott-david-walker** [weaveworks/tf-controller#593]
Is there a manner in which you can add labels and annotations to the outputted secret in a declarative manner? In a similar way that we can do with the 'podrunnertemplate'.

**Comment by chanwit** [comment]
Hi @scott-david-walker 
currently, there is no mechanism to do so.

But yes, it would make a good feature.

**Comment by scott-david-walker** [comment]
Any plans on adding it in the near future? If not, I'd happy to pick it up and make a pr for it?

**Comment by chanwit** [comment]
Thank you so much @scott-david-walker 
Would you mind discussing the API design for it here a bit more?

Maybe something like this:
```yaml
spec:
  writeOutputsToSecret:
    labels:
      my-label: true
    annotations:
      my-annotation: "very long string"
    name: helloworld-output
    outputs:
    - hello_world
    - my_sensitive_data    
```
 what do you think?

**Comment by scott-david-walker** [comment]
That would be my approach as well. 
My only thought would me whether it's worthwhile to have them grouped under a 'metadata' object? Would be a more consequent API considering it's then the same as the 'runnerPodTemplate'
```yaml
spec:
  writeOutputsToSecret:
    metadata:
      labels:
        my-label: true
      annotations:
        my-annotation: "very long string"
    name: helloworld-output
    outputs:
    - hello_world
    - my_sensitive_data    
```
