### ISSUE TITLE
support `hostAliases` in runner pod template

### ISSUE THREAD

**Issue by chanwit** [weaveworks/tf-controller#631]
Currently, we support only a small subset of Pod fields.
We need a capability to specify `hostAliases` in the runner pod template, like this:

```yaml
  hostAliases:
  - hostnames:
   - abc.kubernetes.docker.internal
   - def.kubernetes.docker.internal
   - ijk.kubernetes.docker.internal
```
