### ISSUE TITLE
Using nested variable blocks from a configmap

### ISSUE THREAD

**Issue by Smana** [weaveworks/tf-controller#634]
Hi,

I'm trying to use a module that requires variables with maps, lists ...
Let's say that I want to use this [irsa-eks](https://github.com/terraform-aws-modules/terraform-aws-iam/blob/master/examples/iam-role-for-service-accounts-eks/main.tf#L71) module.
How would I define the variables into a configmap please?
The following code won't work obviously

```yaml
apiVersion: v1
data:
  role_name: "cert-manager"
  attach_load_balancer_controller_policy: true
  oidc_providers:
    ex:
      provider_arn: ${oidc_cluster_issuer}
      namespace_service_accounts: ["kube-system:alb-controller"]
  tags:
    env: ${environment}
    cluster: ${cluster_name}
kind: ConfigMap
metadata:
  name: tfvars-dev-hiving-hen
  namespace: flux-system
```

Thank you

**Comment by chanwit** [comment]
I'll check to see if we would find some good tricks to deserialize structured data as HCL's `map`.

**Comment by Smana** [comment]
Hi @chanwit , thanks for your answer.
Indeed using `vars` works like charm. Here is an example

```yaml
---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: irsa-alb-controller
  namespace: flux-system
spec:
  approvePlan: auto
  destroyResourcesOnDeletion: true
  interval: 8m
  path: ./modules/iam-role-for-service-accounts-eks
  sourceRef:
    kind: GitRepository
    name: terraform-aws-iam
    namespace: flux-system
  vars:
    - name: role_name
      value: ${cluster_name}_load-balancer-controller
    - name: attach_load_balancer_controller_policy
      value: true
    - name: oidc_providers
      value:
        main:
          provider_arn: "arn:aws:iam::396740644681:oidc-provider/oidc.eks.eu-west-3.amazonaws.com/id/334996A8FE74940986820750305976D8"
          namespace_service_accounts: ["kube-system:alb-controller"]
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: terraform-aws-iam
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/terraform-aws-modules/terraform-aws-iam
```

However that would be very useful to source the vars from secrets for example. If the sensitive data is in a nested map.

**Comment by shencan** [comment]
Any updates for this issue, varsFrom only support  configmap value is string, not support hcl map or list.

**Comment by chanwit** [comment]
Hi @shencan 

We still don't have a good solution to this problem. A feasible implementation would be allowing a user to manually add type information to secrets or configmaps, but it would cause another UX problem. No one would want to add that extra info by themselves.

Maybe we would try introducing `.yaml` like this:

```yaml
kind: ConfigMap
data:
  my-config.yaml: |
    regions:
      - us-west-1
      - us-east-1
```

Please note that we will not support parsing HCL in Secrets or ConfigMaps, but we might support conversion of YAML or JSON to HCL.
