### ISSUE TITLE
Broken metrics?

### ISSUE THREAD

**Issue by onedr0p** [weaveworks/tf-controller#639]
Hi again 👋🏼 

I am on `0.15.0-rc.4` and noticed metrics are no longer being scraped. My Helm values are as followed.

```yaml
installCRDs: true
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
```

<img width="1379" alt="image" src="https://github.com/weaveworks/tf-controller/assets/213795/348a3e17-55d7-42c2-ae6e-2c6f4fdd8827">
