### ISSUE TITLE
Consuming an output which is a map

### ISSUE THREAD

**Issue by Smana** [weaveworks/tf-controller#642]
Hello,

I'd like to retrieve the `domain_name` and the `zone_id` from a hosted zone created with the controller.
However I'm struggling getting the proper format. Actually when I use that

```yaml
  writeOutputsToSecret:
    name: route53-cloud-hostedzone
    outputs:
      - route53_zone_name:domain_name
      - route53_zone_zone_id:zone_id
````

I don't get the expected string format

```yaml
apiVersion: v1                                                                                                                                                                                                                                
data:                                                                                                                                                                                                                                         
  domain_name: ewogICAgICAiY2xvdWQub2dlbmtpLmlvIjogImNsb3VkLm9nZW5raS5pbyIKICAgIH0=                                                                                                                                                           
...                                                                                                                         
kind: Secret                                                                                                                                                                                                                                  
metadata:                                                                                                                                                                                                                                     
  name: route53-cloud-hostedzone                                                                                                                                                                                                              
  namespace: flux-system
```

```console
echo ewogICAgICAiY2xvdWQub2dlbmtpLmlvIjogImNsb3VkLm9nZW5raS5pbyIKICAgIH0= |base64 -d
{
      "cloud.ogenki.io": "cloud.ogenki.io"
    }
```

From my understanding I should parse the output within the resource that consumes the secret but I don't know how to proceed.

the module expects the string `domain_name` and `zone_id`
```yaml
kind: Terraform
metadata:
  name: acm-cloud
spec:
  approvePlan: auto
  destroyResourcesOnDeletion: false
  interval: 8m
  path: ./
  sourceRef:
    kind: GitRepository
    name: terraform-aws-acm
    namespace: flux-system
  vars:
    - name: subject_alternative_names
      value:
        - "*.cloud.ogenki.io"
    - name: wait_for_validation
      value: true
    - name: tags
      value:
        Name: "cloud.ogenki.io"
  varsFrom:
    - kind: Secret
      name: route53-cloud-hostedzone
```
