### ISSUE TITLE
[CX] Kustomization trying to apply wrong version of terraform object

### ISSUE THREAD

**Issue by paulcarlton-ww** [weaveworks/tf-controller#656]
See https://github.com/fluxcd/kustomize-controller/issues/881 there seems to an issue applying v1alphav2 tf custom resource using Kustomization

========

**User Story:**

As a Kubernetes user,
I'd like to apply the correct version of Terraform Custom Resource using Kustomization,
so that I can avoid errors during reconciliation and have a smooth experience with Flux v2 and Terraform.

**Acceptance Criteria:**

- [ ] Ensure Kustomization applies the correct version of Terraform Custom Resource
- [ ] Fix reconciliation issues when using Flux v2 and Terraform Custom Resource

**Comment by chanwit** [comment]
@paulcarlton-ww I couldn't find any v1alpha1 references in the controller codes.
How would we replicate this issue?

**Comment by paulcarlton-ww** [comment]
I can recreate it on my MacBook using https://github.com/ww-gitops/paulcarlton-ww-macbook 
This can be deployed on other systems, there is a template repo which is not quite upto date at present but in a good enough state to reproduce from at https://github.com/ww-gitops/gitops-wge-cluster-template or you could try and recreate it by using the yaml below, you could probably simplify it, it doesn't need to work, you just need to apply it using Flux (or not), the important element is the HostAliases element that is not supported in v1alpha1

```
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  finalizers:
  - finalizers.tf.contrib.fluxcd.io
  labels:
    kustomize.toolkit.fluxcd.io/name: test-eks-config-c1
    kustomize.toolkit.fluxcd.io/namespace: test-two
  name: eks-config-test-c1
  namespace: test-two
spec:
  alwaysCleanupRunnerPod: true
  approvePlan: auto
  backendConfig:
    customConfiguration: |
      backend "s3" {
        key            = "ww-paulc-macbook/test-two/eks-config/test/c1/terraform.tfstate"
        bucket         = "ww-paulc-ac-749339757188-eu-west-1-tf-state"
        region         = "eu-west-1"
        encrypt        = true
        dynamodb_table = "ww-paulc-ac-749339757188-eu-west-1-tf-state"
      }
  dependsOn:
  - name: eks-test-c1
  destroyResourcesOnDeletion: true
  disableDriftDetection: false
  force: false
  interval: 10m
  parallelism: 0
  path: ./terraform/cluster-templates/eks-config
  refreshBeforeApply: false
  retryInterval: 20s
  runnerPodTemplate:
    spec:
      envFrom:
      - secretRef:
          name: aws-creds
      hostAliases:
      - hostnames:
        - dex.kubernetes.docker.internal
        - wge.kubernetes.docker.internal
        - vault.kubernetes.docker.internal
        ip: 10.105.127.50
      volumeMounts:
      - mountPath: /etc/ssl/certs/local-ca.pem
        name: local-ca
        subPath: CA.cer
      volumes:
      - configMap:
          defaultMode: 420
          name: local-ca
        name: local-ca
  runnerTerminationGracePeriodSeconds: 30
  serviceAccountName: tf-runner
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  storeReadablePlan: none
  vars:
  - name: tags
    value:
      creator: paul.carlton@weave.works
      customer: weaveworks-cx
      projectGid: 20276
  - name: cluster_name
    value: test-c1
  - name: resource_name
    value: test
  - name: template_namespace
    value: test-two
  - name: region
    value: eu-west-1
  - name: target_path
    value: clusters/test-two/test/c1
  - name: desired_size
    value: "2"
  - name: eks_core_state_bucket
    value: ww-paulc-ac-749339757188-eu-west-1-tf-state
  - name: eks_core_state_key
    value: ww-paulc-macbook/test-two/eks/test-c1/terraform.tfstate
  varsFrom:
  - kind: ConfigMap
    name: leaf-cluster-config
    varsKeys:
    - git_commit_author
    - git_commit_email
    - github_owner
    - github_org
    - repository_name
    - cluster_admin_users_string
  - kind: Secret
    name: github-leaf-token
    varsKeys:
    - github_token
  - kind: Secret
    name: vault-token
  - kind: ConfigMap
    name: cluster-config
  workspace: default
  writeOutputsToSecret:
    name: test-c1-cluster-config
```
