### ISSUE TITLE
Introducing runtime namespace env variable and downward map Pod namespace to the variable

### ISSUE THREAD

**Issue by chanwit** [weaveworks/tf-controller#762]
**User Story:**
As a Kubernetes cluster administrator, I want to introduce a new environment variable, RUNTIME_NAMESPACE, that will map the Pod's namespace at runtime so that my microservices can be more aware of their deployed environment.

**Acceptance Criteria:**
  - The system should introduce a new environment variable named RUNTIME_NAMESPACE.
  - The RUNTIME_NAMESPACE environment variable should automatically map the namespace of the Pod at runtime.
  - The value of RUNTIME_NAMESPACE should be dynamically derived from the Pod's `metadata.namespace` field.

```yaml
        env:
        - name: RUNTIME_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
```
