### ISSUE TITLE
Source gets deleted instantly for branch planner

### ISSUE THREAD

**Issue by yitsushi** [weaveworks/tf-controller#779]
I don't know why, but the GitReposiotry Source is cloned and then instantly deleted.

Resources: 
```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ef-helloworld
  namespace: terraform
spec:
  interval: 30s
  url: ssh://git@github.com/yitsushi/tf-controller-helloworld
  secretRef:
    name: ssh-access
  ref:
    branch: main
---
apiVersion: v1
kind: Secret
metadata:
  name: ef-helloworld-tf
  namespace: terraform
stringData:
  test-data: "test"
---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: ef-helloworld-tf
  namespace: terraform
spec:
  path: ./
  interval: 20s
  approvePlan: auto
  sourceRef:
    kind: GitRepository
    name: ef-helloworld
    namespace: terraform
  vars:
  - name: secret_subject
    value: "test-"
  varsFrom:
  - kind: Secret
    name: ef-helloworld-tf
    varsKeys:
    - test-data:subject
  writeOutputsToSecret:
    name: ef-helloworld-tf-outputs
  runnerPodTemplate:
    metadata:
      labels:
        instance: ef-helloworld-tf # This is the name of the Terraform resource
    spec:
      image: ghcr.io/weaveworks/tf-runner
```

The `ssh-access` secret an identity with ssh key.

```
❯ kubectl get gitrepository -n terraform
NAME                             URL                                                      AGE     READY   STATUS
ef-helloworld                    ssh://git@github.com/yitsushi/tf-controller-helloworld   99s     True    stored artifact for revision 'main@sha1:a570bd81090f78cf9276dc61a0f0c1ce59d56df4'
helloworld                       https://github.com/tf-controller/helloworld              2m43s   True    stored artifact for revision 'main@sha1:3ac83e0ff205dcd2e21f08120312e3502f62a9e2'
helloworld-test-placeholder-11   https://github.com/tf-controller/helloworld              25s     True    stored artifact for revision 'test-placeholder@sha1:5e97cd349620ff67b7b088bc053c60b7bb73335b'

❯ flux get sources git -n terraform
NAME                            REVISION                        SUSPENDED       READY   MESSAGE
ef-helloworld                   main@sha1:a570bd81              False           True    stored artifact for revision 'main@sha1:a570bd81'
helloworld                      main@sha1:3ac83e0f              False           True    stored artifact for revision 'main@sha1:3ac83e0f'
helloworld-test-placeholder-11  test-placeholder@sha1:5e97cd34  False           True    stored artifact for revision 'test-placeholder@sha1:5e97cd34'


❯ kubectl get terraforms.infra.contrib.fluxcd.io -n terraform
NAME                                  READY     STATUS                                    AGE
ef-helloworld-tf                      Unknown   Reconciliation in progress                85s
ef-helloworld-tf-yitsushi-patch-1-1   False     Source is not ready, artifact not found   71s
helloworld-tf                         Unknown   Reconciliation in progress                2m29s
helloworld-tf-test-placeholder-11     Unknown   Deletion in progress                      2m11s
```

Logs:
```
{"level":"info","ts":"2023-07-14T14:39:04.826Z","logger":"polling-server","msg":"checking Terraform object","version":"v0.15.1-50-g7054418","sha":"7054418","namespace":"terraform","name":"ef-helloworld-tf"}
{"level":"info","ts":"2023-07-14T14:39:04.826Z","logger":"polling-server","msg":"start polling","version":"v0.15.1-50-g7054418","sha":"7054418","namespace":"terraform","name":"ef-helloworld-tf"}
{"level":"info","ts":"2023-07-14T14:39:04.826Z","logger":"polling-server","msg":"fetching terraform object","version":"v0.15.1-50-g7054418","sha":"7054418","namespace":"terraform","name":"ef-helloworld-tf"}
{"level":"info","ts":"2023-07-14T14:39:04.827Z","logger":"polling-server","msg":"fetching source object","version":"v0.15.1-50-g7054418","sha":"7054418","namespace":"terraform","name":"ef-helloworld-tf"}
{"level":"info","ts":"2023-07-14T14:39:04.847Z","logger":"informer","msg":"Plan not updated","version":"v0.15.1-50-g7054418","sha":"7054418","namespace":"terraform","name":"ef-helloworld-tf-yitsushi-patch-1-1","pr-id":"1"}
{"level":"info","ts":"2023-07-14T14:39:05.087Z","logger":"polling-server","msg":"Source ef-helloworld-yitsushi-patch-1-1 in the namespace terraform successfully reconciled","version":"v0.15.1-50-g7054418","sha":"7054418","operation":"created"}
{"level":"info","ts":"2023-07-14T14:39:05.163Z","logger":"informer","msg":"Plan not updated","version":"v0.15.1-50-g7054418","sha":"7054418","namespace":"terraform","name":"ef-helloworld-tf-yitsushi-patch-1-1","pr-id":"1"}
{"level":"info","ts":"2023-07-14T14:39:05.492Z","logger":"polling-server","msg":"checking Terraform object","version":"v0.15.1-50-g7054418","sha":"7054418","namespace":"terraform","name":"ef-helloworld-tf-yitsushi-patch-1-1"}
{"level":"info","ts":"2023-07-14T14:39:05.784Z","logger":"polling-server","msg":"deleted Source ef-helloworld-yitsushi-patch-1-1 in the namespace terraform","version":"v0.15.1-50-g7054418","sha":"7054418"}
{"level":"info","ts":"2023-07-14T14:39:05.794Z","logger":"polling-server","msg":"deleted Terraform ef-helloworld-tf-yitsushi-patch-1-1 in the namespace terraform","version":"v0.15.1-50-g7054418","sha":"7054418"}
{"level":"info","ts":"2023-07-14T14:39:05.794Z","logger":"polling-server","msg":"successfully deleted Terraform object","version":"v0.15.1-50-g7054418","sha":"7054418","name":"ef-helloworld-tf-yitsushi-patch-1-1","namespace":"terraform","PR ID":"1"}
```
