### ISSUE TITLE
`.spec.vars` is not working properly

### ISSUE THREAD

**Issue by tomhuang12** [weaveworks/tf-controller#80]
Tried setting `vars` to the followings:

```
  vars:
  - name: region
    value: us-east-1
```
and 
```
vars:
  - name: cluster_spec
    value:
      region: us-east-1
      env: dev
      node_count: 10
      public: false
```

Both resulted the following error:
```
E0203 04:57:12.795883       7 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.Terraform: failed to list *v1alpha1.Terraform: json: cannot unmarshal object into Go struct field Variable.items.spec.vars.value of type string
```
