### ISSUE TITLE
ConfigMap not found. The default configmap should be generated by the HelmChart if branch planner enabled

### ISSUE THREAD

**Issue by chanwit** [weaveworks/tf-controller#828]
This ConfigMap should be generated by default as part of the HelmChart.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: branch-planner
  namespace: flux-system
data:
  secretName: branch-planner-token
  resources:  -
    - namespace: flux-system
```
