### ISSUE TITLE
Cluster scoped roles and cluster-admin RoleBinding in reconciler

### ISSUE THREAD

**Issue by SebastianBakala-TomTom** [weaveworks/tf-controller#833]
1. Is it possible to run controllers on non-ClusterScoped roles?

2. Does the reconciler really needs cluster-admin role?
https://github.com/weaveworks/tf-controller/blob/main/charts/tf-controller/templates/rbac.yaml#L170

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tf-cluster-reconciler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: {{ include "tf-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
```
