### ISSUE TITLE
Custom service account for runner fails with access error to secret "terraform-runner.tls-*"

### ISSUE THREAD

**Issue by yehoshuadimarsky** [weaveworks/tf-controller#844]
I'm specifying the `serviceAccountName` and running into this error:

```
secrets "terraform-runner.tls-1691764889" is forbidden: User "system:serviceaccount:flux-system:gcp-service-acct" cannot get resource "secrets" in API group "" in the namespace "flux-system"
```

my namespace is `flux-system`, my SA is named `gcp-service-acct`. The docs don't clarify what permissions I'm supposed to give my SA if I'm using one, so I'm at a loss here. Thanks!

========

**User Story:**

As a Kubernetes cluster administrator,
I'd like to use a custom ServiceAccount for Terraform Controller runners,
so that I can manage access to my Kubernetes resources more effectively.

**Acceptance Criteria:**

- [ ] Custom ServiceAccount can be specified for runner
- [ ] Custom ServiceAccount needs to have the appropriate RBAC applied
- [ ] Add clear documentation about necessary permissions for custom ServiceAccounts
- [ ] The Helm chart should allow easy customization for custom ServiceAccount usage

**Comment by chanwit** [comment]
Hi @yehoshuadimarsky 

It seems you didn't install the controller via our supported Helm chart?

If so, please refer to the RBAC defined here for your setup.

https://github.com/weaveworks/tf-controller/blob/main/charts/tf-controller/templates/rbac.yaml

**Comment by yehoshuadimarsky** [comment]
thanks, yeah it turned out to be RBAC, I just added a `ClusterRoleBinding` to my SA using the ClusterRole named `tf-runner-role` and it worked

**Comment by yehoshuadimarsky** [comment]
Weird actually, cuz I did in fact use the helm chart, here's my `kusomization.yaml`:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
helmCharts:
  - includeCRDs: true
    name: flux2
    namespace: flux-system
    repo: https://fluxcd-community.github.io/helm-charts/
    version: 2.9.2
  - includeCRDs: true
    name: tf-controller
    namespace: flux-system
    repo: https://weaveworks.github.io/tf-controller/
    version: 0.15.1
kind: Kustomization
namespace: flux-system
```
