### ISSUE TITLE
How to view saved TF Plan in plan only mode?

### ISSUE THREAD

**Issue by yehoshuadimarsky** [weaveworks/tf-controller#847]
My setup:

```yaml
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: main
  namespace: flux-system
spec:
  backendConfig:
    customConfiguration: |
      backend "gcs" {
        bucket = "MYBUCKET"
      }
  fileMappings:
    - location: "home"
      path: ".ssh/id_rsa"
      secretRef:
        key: identity
        name: flux-gh-infra-core-secret
    - location: "home"
      path: ".ssh/known_hosts"
      secretRef:
        key: known_hosts
        name: flux-gh-infra-core-secret
  interval: 1m
  path: ./tf/dev
  planOnly: true
  serviceAccountName: gcp-service-acct
  sourceRef:
    kind: GitRepository
    name: infra-live
    namespace: flux-system
  storeReadablePlan: human
```

1. The documentation is pretty barebones (put nicely), could be much improved
    1. I had no idea what the valid values for `storeRedadablePlan` were until I literally searched the codebase to figure it out (`human` or `json`).
    1. Also had no idea how to use `fileMappings` until I found (after hours of searching) this comment https://github.com/weaveworks/tf-controller/issues/556#issuecomment-1486225250
1. To my real point - I can get it to run and generate a plan, how do I view it? It seems to be outputting it to a Secret but I can't view it. Tried this (inspired by https://gist.github.com/DzeryCZ/c4adf39d4a1a99ae6e594a183628eaee) 
```zsh
kubectl get secret tfplan-default-main -n flux-system -o json | jq .data.tfplan | tr -d '"' | base64 -d | gzip -d > tfplan1
terraform show tfplan1
```

which gives me

```
╷
│ Error: Failed to read the given file as a state or plan file
│
│ State read error: Error reading tfplan1 as a statefile: 2 problems:
│
│ - Unsupported state file format: The state file could not be parsed as JSON: syntax error at byte offset 1.
│ - Unsupported state file format: The state file does not have a "version" attribute, which is required to identify the format version.
│
│ Plan read error: plan file was created by Terraform 1.3.9, but this is 1.5.4; plan files cannot be transferred between different Terraform versions
```

So I tried using a Docker container:
```zsh
docker run --rm -v ~/Desktop/tfplan-temp:/tmp/tfplan-temp hashicorp/terraform:1.3.9 show /tmp/tfplan-temp/tfplan1
```

No dice:
```
╷
│ Error: Failed to load plugin schemas
│
│ Error while loading schemas for plugin components: 2 problems:
│
│ - Failed to obtain provider schema: Could not load the schema for provider
│ registry.terraform.io/hashicorp/google: failed to instantiate provider
│ "registry.terraform.io/hashicorp/google" to obtain schema: unavailable
│ provider "registry.terraform.io/hashicorp/google".
│ - Failed to obtain provider schema: Could not load the schema for provider
│ registry.terraform.io/hashicorp/time: failed to instantiate provider
│ "registry.terraform.io/hashicorp/time" to obtain schema: unavailable
│ provider "registry.terraform.io/hashicorp/time"..
╵
```

My I be so bold to ask what's the **intended** usage of this feature? Or am I missing something basic?
