### ISSUE TITLE
Make the backend configurable

### ISSUE THREAD

**Issue by chanwit** [weaveworks/tf-controller#97]
Currently we support only Kubernetes backend.
But some users still require to use their existing backends like S3 or Dynamo tables outside Kubernetes.

It would be great to make the backend configurable to support those existing systems.

Here's a possible API design for custom backend.
```yaml
---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: tf-controller-ng-cc5a1ac4
  namespace: flux-system
spec:
  interval: 1h
  path: ./_artifacts/20-zz-terraform
  approvePlan: "auto"
  backend:
    customConfiguration: |
      backend "s3" {
        bucket = "mybucket"
        key    = "path/to/my/key"
        region = "us-east-1"
      }
  varsFrom:
  - kind: Secret
    name: aws-vars
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
```
